### ISSUE TITLE
Creating a Frontend and backend for login/signup page

### ISSUE THREAD

**Issue by bilalshaikh292** [samarthhapse/sarthi#10]
first, we create a frontend and then the backend.MongoDB connection will be done in the backend part.

**Comment by bilalshaikh292** [comment]
@samarthhapse please provide me with a design and more details so that I can start working.

**Comment by AbhiDiva96** [comment]
Hii @samarthhapse  I am excited to contribute in this project which is close to my heart as I am interested in mern stack developement.

I will built it thoroughly sigin and signup page from frontend to backend.

Frontend 
React
Tailwind 
Typescript 

Backend 
Node js
Mongodb 
Jwt library for authentication 
(Token functionality)


Pls assign me this issue.

**Comment by bilalshaikh292** [comment]
@AbhiDiva96 I have created this issue to create a PR for this . I am already working on this issue . I appreciate your skills and passion and I suggest you to work on some other issue.

**Comment by AbhiDiva96** [comment]
Ok bro u proceed with it

**Comment by IP80808080** [comment]
👋 Hello! I'd be happy to help with this issue. Could you please assign it to me? Additionally, could you please label it for the appropriate level? Thank you! 🚀

**Comment by Anup2601** [comment]
I would like to work on this issue, please assign this issue to me under GSSoC'24.

**Comment by samarthhapse** [comment]
@bilalshaikh292 once let me add UI design in Learn.md then you can start working on this issue

**Comment by Jatingupta9120** [comment]
assign this issue to me

**Comment by poojaverma9578** [comment]
I would like to make an impactful contribution to this project.Please assign me this.

**Comment by bilalshaikh292** [comment]
ok @samarthhapse Just ping me once after that

**Comment by Mandar007007** [comment]
i have a quite good experience with this task could you please assign me this task as a part of gssoc24

**Comment by Chandan157** [comment]
Hello sir, I am Chandan. Under GSSOC'24, I would like to work on this issue. can you assign this issue to me!!

**Comment by bilalshaikh292** [comment]
@Chandan157 Please read the message from the start and try to understand whats going on .

**Comment by samarthhapse** [comment]
> ok @samarthhapse Just ping me once after that

sure @bilalshaikh292

**Comment by viththagi** [comment]
Hi @samarthhapse I would like to work on this issue My stack would be:

Front End: React
Back End: Express.js,Node.js,MongoDB 
mongoDB connections will be done using mongoose library.

**Comment by mtg718** [comment]
hi@samarthhapse 
Please assign this issue to me under GSSoC'24.

**Comment by samarthhapse** [comment]
@bilalshaikh292 create login and signup page (with options to login /signup as 1.learner 2.expert). Add dummy input areas. for both learner and expert as per your convenience. Complete it with complete frontend and backend. What date should I expect for completion of this task from your side ?

**Comment by bilalshaikh292** [comment]
I will start and update you

**Comment by ayann07** [comment]
@samarthhapse I have already done backend for the same, kindly check my pull request .

**Comment by samarthhapse** [comment]
Hello @bilalshaikh292 , I have merged the pull request of ayann , now you can fork and create frontend of login and signup page accordingly

**Comment by samarthhapse** [comment]
@bilalshaikh292 comment here if you have any issue in connection with backend, @ayann07 please collaborate and help him in case of any issue with the connection of the backend created by you

**Comment by samarthhapse** [comment]
@bilalshaikh292 have you started ? so I can assignees

**Comment by Yuvraj960** [comment]
@samarthhapse , Hello, I can fix this issue by attaching the mongoDB for validating the login/signup responses

**Comment by tanvikoranne** [comment]
I would like to work upon this issue. Please assign me this issue.

**Comment by samarthhapse** [comment]
@bilalshaikh292  reminder 2 : have you started working?

**Comment by bilalshaikh292** [comment]
@samarthhapse Sorry for not replaying .I am not working on this issue you can assign it some one else

**Comment by Yuvraj960** [comment]
@samarthhapse You can assign this issue to me.

**Comment by samarthhapse** [comment]
@IP80808080 , @AbhiDiva96 , @Jatingupta9120 is anyone available for this issue

**Comment by samarthhapse** [comment]
But the thing is you have to design pages according to backend

**Comment by AbhiDiva96** [comment]
yaa I got it. i will do it from scratch you can assigned to me.
@samarthhapse

**Comment by samarthhapse** [comment]
no need to do from scratch , it is to be done according to the backend code

**Comment by AbhiDiva96** [comment]
ok got it. as you wish i will do it according to backend code

**Comment by samarthhapse** [comment]
okay @AbhiDiva96 , I have assigned it ! You can start building

**Comment by samarthhapse** [comment]
Comment here with the expected date of submission from your side

**Comment by AbhiDiva96** [comment]
i have started building it. I will finish it by Sunday(27/05/24)
@samarthhapse

**Comment by AbhiDiva96** [comment]
hey @samarthhapse 
I have built the frontend authorization according to the backend requirements.
pls, review it.

**Comment by samarthhapse** [comment]
great ! @AbhiDiva96 can I please get ss of expert signup page

**Comment by AbhiDiva96** [comment]
yaah sure. @samarthhapse 
I am updating PR with expert signup page.You can check there.

**Comment by samarthhapse** [comment]
btw I have labeled your PR with "gssoc & level2" which will help you to gain some extra points on the leaderboard, once check out my comment on your PR.

**Comment by AbhiDiva96** [comment]
tq so much @samarthhapse

**Comment by samarthhapse** [comment]
Hello everyone there , comment on https://github.com/samarthhapse/sarthi/issues/20 if you are experienced in advanced react and tailwind and willing to work on same signup and login page to update the old simple one in to the super cool page with attention seeking animations and much more changes in UI only

**Comment by samarthhapse** [comment]
hello @AbhiDiva96

**Comment by samarthhapse** [comment]
@AbhiDiva96  I asked you to wait for 2 days , I have an issue for you.

**Comment by samarthhapse** [comment]
@AbhiDiva96  Raising PR for this issue can help you to get assignee for another 2 issues related to this one. Comment below if you are wiling to create it. I will create an issue and assign it to you

**Comment by AbhiDiva96** [comment]
Hey @samarthhapse 
Thankyou for the opportunity. I am willing to do but my semester examination has been started. So I am unable to do it between 11 June to 26 June (these 15day crucial for me as a contributor). As my examination will be over I will back to you.
Thankyou so much.

**Comment by samarthhapse** [comment]
Okay @AbhiDiva96 , get done with the exams first.All the best for exams.

**Comment by AbhiDiva96** [comment]
Thankyou so much
