### ISSUE TITLE
feat: REVAMP THE HOME PAGE

### ISSUE THREAD

**Issue by AbhinaySngh** [samarthhapse/sarthi#105]
![Screenshot 2024-06-06 133344](https://github.com/samarthhapse/sarthi/assets/162811933/69e4b32a-064a-4def-936b-941e926d5c8a)

**Comment by AbhinaySngh** [comment]
@samarthhapse please assign me this issue under GSSOC'24 label.

**Comment by samarthhapse** [comment]
@AbhinaySngh I have assigned this issue already to someone else

**Comment by AbhinaySngh** [comment]
Ok

**Comment by AbhinaySngh** [comment]
@samarthhapse can i add footer section in home page.
