### ISSUE TITLE
Fixing the UI of whole app

### ISSUE THREAD

**Issue by VaibhavYT** [samarthhapse/sarthi#107]
Assign this fixing and please add gssoc label 😁✅

Although I am working on adding animations
You can look here:

## Before
![Homepage before](https://github.com/samarthhapse/sarthi/assets/78371075/6d9b09c1-2226-49f0-9e21-a44e6105408f)
![Landing Page before](https://github.com/samarthhapse/sarthi/assets/78371075/44ac37da-e04b-473f-ad70-0943b7bcb032)

## After

![HomePage UI after](https://github.com/samarthhapse/sarthi/assets/78371075/48865d10-2e65-46b9-986b-f229e5a7bccb)
![Landing Page UI after](https://github.com/samarthhapse/sarthi/assets/78371075/31562c13-31d2-4a62-a292-97314c7de1c1)

**Comment by VaibhavYT** [comment]
Please give tag to this created issue and assign me please I will create an PR for this

**Comment by samarthhapse** [comment]
I have assigned it to you. But for next two days strictly do not work on the home page, instead of home you can work more better on sign-in and sign-up page UI (make it dark themed and try to add more animations cool (3D if possible)). Within next two days another contributor is adding new home page then I will tell you to add animations in home page

**Comment by samarthhapse** [comment]
@VaibhavYT  till then 9 EOD work on sign-up and sign-in pages only

**Comment by VaibhavYT** [comment]
Ok for this issue I am raising an PR and for making 3d animation or more enhanced animation I will open an issue , then you will please assign.

**Comment by samarthhapse** [comment]
ok , sure

**Comment by samarthhapse** [comment]
@VaibhavYT you can take reference from here. Just change UI do not change the code logic (backend code should not crash). Create it in dark theme

**Comment by samarthhapse** [comment]
@VaibhavYT 
For  reference=>

https://dribbble.com/search/dark-theme-login

**Comment by VaibhavYT** [comment]
https://dribbble.com/shots/22066365-Login-Screen-Dark-Theme
what about this ?
