### ISSUE TITLE
three.js UI integration

### ISSUE THREAD

**Issue by samarthhapse** [samarthhapse/sarthi#113]

**Comment by VaibhavYT** [comment]
IN which place you want to have the 3D Component?

**Comment by samarthhapse** [comment]
![Screenshot_20240616_101413_GitHub.jpg](https://github.com/samarthhapse/sarthi/assets/131296047/d569d9c9-63ae-4b6d-9c0a-7c322988b62b)

on this page , with dark bluish background and 3D avatar of student on left and expert on right

**Comment by samarthhapse** [comment]
![Screenshot_20240616_101745_Chrome.jpg](https://github.com/samarthhapse/sarthi/assets/131296047/83e42f20-0834-4e1f-ae0c-049b0f3b01f8)

For example

**Comment by samarthhapse** [comment]
![Screenshot_20240616_101745_Chrome.jpg](https://github.com/samarthhapse/sarthi/assets/131296047/83e42f20-0834-4e1f-ae0c-049b0f3b01f8)

For example only

**Comment by VaibhavYT** [comment]
Ok got it, I can do this without 3.js because 3..js will make website too slow

**Comment by samarthhapse** [comment]
Yes , you can proceed
