### ISSUE TITLE
adding backend features

### ISSUE THREAD

**Issue by samarthhapse** [samarthhapse/sarthi#114]

**Comment by Jagpreet153** [comment]
@samarthhapse Could you please elaborate the features you are asking about

**Comment by samarthhapse** [comment]
multiple entries are getting update in DB ,so  just listing that updates on frontend page

**Comment by Jagpreet153** [comment]
Ok , I would like to work on the issue .

**Comment by samarthhapse** [comment]
Okay , just wait till 8 EOD. If necessary for app , I will assign this to you only her !

**Comment by samarthhapse** [comment]
Now let's get on #115

**Comment by Jagpreet153** [comment]
@samarthhapse Kindly assign this issue to me

**Comment by samarthhapse** [comment]
TASK : after student login he must get three sections to choose 
1.Bug solving
2.Tech career assistance
3.Academic support
after selecting the section from above mentioned options , student must get list of all experts available in DB for the specific option

**Comment by samarthhapse** [comment]
While signing in of experts they have three field to select,  you have to display them to student accordingly who login and select one section among three of them

**Comment by samarthhapse** [comment]
@Jagpreet153 can you do it by 9 EOD

**Comment by samarthhapse** [comment]
If yes , pls comment below and you can start working. I will assign it to you.

**Comment by samarthhapse** [comment]
If yes , pls comment below and you can start working. I will assign it to you.

**Comment by Jagpreet153** [comment]
> @Jagpreet153 can you do it by 9 EOD

But 9 is today give till 11

**Comment by samarthhapse** [comment]
@Jagpreet153 you can complete till 11 EOD , but don't opt for 12. Raise PR by 11 itself

**Comment by samarthhapse** [comment]
Any progress? @Jagpreet153

**Comment by samarthhapse** [comment]
Keep updating here

**Comment by samarthhapse** [comment]
hello @Jagpreet153 any update ? how much of it is completed

**Comment by samarthhapse** [comment]
@Jagpreet153 just tell me if you aren't working on this task

**Comment by Jagpreet153** [comment]
Sorry @samarthhapse .I am busy at some other work so could'nt complete the task on time

**Comment by samarthhapse** [comment]
Okay @Jagpreet153 you can take time till 13 EOD . But it's last deadline. Please complete it as first priority

**Comment by samarthhapse** [comment]
@Jagpreet153 completing today ?

**Comment by Jagpreet153** [comment]
@samarthhapse There is error in signup page of student

**Comment by samarthhapse** [comment]
@Jagpreet153 , currently this issue is resolved , if any another backend related issue opens, I will comment here
