### ISSUE TITLE
404 page

### ISSUE THREAD

**Issue by Jagpreet153** [samarthhapse/sarthi#115]
I would like to add a 404 error page it would consist of animated with proper message . Kindly assign this task to me under GSSoC'24

**Comment by samarthhapse** [comment]
@Jagpreet153 are you familiar with Node , Express and mongoDb

**Comment by Jagpreet153** [comment]
Yes @samarthhapse

**Comment by samarthhapse** [comment]
Okay , @Jagpreet153 you can start working , I am assigning this issue to you. Try to create the page more attractive (3D if possible). But dark theme is complulsary

**Comment by samarthhapse** [comment]
Now you can start. Try to complete it by 8 EOD

**Comment by Jagpreet153** [comment]
ok

**Comment by iLakshya** [comment]
@Jagpreet153 Please assign this issue to me
