### ISSUE TITLE
MERN integrations

### ISSUE THREAD

**Issue by samarthhapse** [samarthhapse/sarthi#116]

**Comment by Shoaibxaif** [comment]
@samarthhapse provide me this issue

**Comment by samarthhapse** [comment]
@Shoaibxaif I have to merge one PR within next 2 days. I will assign this issue to you after 8 EOD.
Till then just go through the code.

**Comment by Shoaibxaif** [comment]
okay

**Comment by samarthhapse** [comment]
@Shoaibxaif ,do you have experience in integration of chat feature integration in web apps (MERN stack) ?

**Comment by samarthhapse** [comment]
@Shoaibxaif , why you aren't replying

**Comment by samarthhapse** [comment]
@Shoaibxaif , I have a better level 3 MERN issue for you

**Comment by samarthhapse** [comment]
@Shoaibxaif you must reply

**Comment by samarthhapse** [comment]
@Shoaibxaif I will assign it to you

**Comment by samarthhapse** [comment]
@Shoaibxaif , no reply ?

**Comment by samarthhapse** [comment]
@Shoaibxaif , you commented by own and not replying now.

**Comment by samarthhapse** [comment]
@Shoaibxaif ok then , can I close this issue ?

**Comment by Shoaibxaif** [comment]
What is the task? Mern integration or chatbot integration

**Comment by samarthhapse** [comment]
Payment gateway integration #201

**Comment by samarthhapse** [comment]
@Shoaibxaif , if you can , pls comment on #201 , I will assign it to you

**Comment by samarthhapse** [comment]
@Shoaibxaif , again no response

**Comment by samarthhapse** [comment]
@Shoaibxaif it's better chance to get level3 issue resolved just by integrating gateway

**Comment by samarthhapse** [comment]
@Shoaibxaif , just comment on that issue
