### ISSUE TITLE
Modern Dark UI of SIgnIn and SignUP pages

### ISSUE THREAD

**Issue by VaibhavYT** [samarthhapse/sarthi#119]
Please assign me this issue I will try to make decent UI of pages. 
please also add gsoc label and also good level if possible ✅😁

**Comment by VaibhavYT** [comment]
I will take reference form #107

**Comment by samarthhapse** [comment]
I am merging #118 , but you should not raise PR for such minor changes.

For this issue => 

take reference from => https://dribbble.com/shots/22066365-Login-Screen-Dark-Theme

Here if you create much attractive UI then I will add level 2 label on your PR.
If you add 3D animated UI effects then I will add level 3.

NOTE : do not change any logic in these files , just handle UI part. Backend should function as earlier only.

**Comment by VaibhavYT** [comment]
I will try to similar UI and also after UI will try to add some cool 3d animations .

**Comment by samarthhapse** [comment]
Sure , you can start now !

**Comment by VaibhavYT** [comment]
You want 1 color dark or any other dark bg like black or something like github dark more 

## This dark mode 1
![Dark-blue](https://github.com/samarthhapse/sarthi/assets/78371075/38db0d39-be21-4099-a6a2-e49d3046d8da)

**Comment by VaibhavYT** [comment]
The color you choose I will make auth page with that color

**Comment by samarthhapse** [comment]
![glassy](https://github.com/samarthhapse/sarthi/assets/131296047/a833b791-a48e-492e-ad66-d1948e71c415)

I am expecting something like this one

**Comment by VaibhavYT** [comment]
Ok sure

**Comment by VaibhavYT** [comment]
What about this?

##Image 
![Signin page after](https://github.com/samarthhapse/sarthi/assets/78371075/86b85493-d568-49fa-94a8-c5b0b05e524b)
## AppVideo

https://github.com/samarthhapse/sarthi/assets/78371075/b59013a5-0ff2-499a-bc3a-bc43e59ad5ab

**Comment by VaibhavYT** [comment]
@samarthhapse please give feedback

**Comment by samarthhapse** [comment]
Nice ! just change the green into violet and Raise PR.

**Comment by VaibhavYT** [comment]
If you liked the UI please Increase the level of tag😁

**Comment by VaibhavYT** [comment]
And also my other two which I resolved and you meged the PR but I think due to issue is open my contribution is not count .
please also resolve that
