### ISSUE TITLE
Implementing a website chatbot for user guidance, home page familiarization 

### ISSUE THREAD

**Issue by Leorasaharia** [samarthhapse/sarthi#12]
1)Addition of a proper chatbot which pops up when a user visits the website which navigates them with the website and gives an insight what the website is about.
2) changing a bit of the home page (landing page of the website) to familiarize others with the perspective of the website.

**Comment by Leorasaharia** [comment]
@samarthhapse kindly consider my views on this! would be looking forward to contribute and enhance your project!

**Comment by IP80808080** [comment]
👋 Hello! I'd be happy to help with this issue. Could you please assign it to me? Additionally, could you please label it for the appropriate level? Thank you! 🚀

**Comment by anshdeep0504** [comment]
Hey, allow me to work on this under GSSOC' 2024
