### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by dishathakurata** [samarthhapse/sarthi#127]
**Describe the bug**
There is a typo "ustoday" is written together with no space in between.

**Expected behavior**
There should be a space between "us" and "today".

**Screenshots**
![us today](https://github.com/samarthhapse/sarthi/assets/146114938/380d936b-6170-403f-9882-dd093e7ab187)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

Assign this issue to me under GSSoC'24.

**Comment by Rachad-Alabi-ADEKAMBI** [comment]
in which file please ?
