### ISSUE TITLE
[GSSOC] [Feature] :Adding a google sign in and sign up option

### ISSUE THREAD

**Issue by divyanshu255** [samarthhapse/sarthi#128]

**Comment by divyanshu255** [comment]
i want to work on this issue under GSSOC24

**Comment by ROKUMATE** [comment]
@samarthhapse Is this Same As that of #60 Issue ? 
about the Google Auth ? 
If So i will request u to assign mee this issue as i have experience in the backend and frontend of the google auth.

**Comment by samarthhapse** [comment]
yes @ROKUMATE , I am assigning this issue to you pls , complete it till 11 EOD

**Comment by samarthhapse** [comment]
Hello @ROKUMATE completed ?
Deadline was 11 EOD still the PR is not raised.
Raise the PR on temp branch

**Comment by ROKUMATE** [comment]
@samarthhapse working on it sir

**Comment by samarthhapse** [comment]
@ROKUMATE it is 13th deadline was 11 only

**Comment by samarthhapse** [comment]
@ROKUMATE make hurry please

**Comment by ROKUMATE** [comment]
@samarthhapse sir i have texted u the issue on linkedin ...

**Comment by samarthhapse** [comment]
@ROKUMATE you can take time till Wednesday

**Comment by samarthhapse** [comment]
@divyanshu255 , can you work to create chat functionality for the chat between student and expert. A level 3 issue.

**Comment by samarthhapse** [comment]
@ROKUMATE , Your task was , when the student/user try to signup/sign-in they should get the option to signup with google option

**Comment by samarthhapse** [comment]
@ROKUMATE the PR I merged today as regarding the updation of expert profile after the signin/ signup process. Both issues are completely different

**Comment by samarthhapse** [comment]
@ROKUMATE , In your PR have you created signin/signup pages again of your own ? . It was only expected to add (signup/signin with google) feature in old pages of signin/signup

**Comment by ROKUMATE** [comment]
sir i have not created another pages ... u later on told that I mentioned another issue over there ... regarding the 

I have used dummy data ... When the user is logged in using google ... we get only his profile photo, username, email
not the other details of phone no. , his job and all ...

so u told that for that u only solve the issue naa ... 
for that only I was creating the expert profile and student profile pages
