### ISSUE TITLE
merging and fixing the UI of 2 pages (code is available , just merge two pages into one ) + fixing the UI

### ISSUE THREAD

**Issue by samarthhapse** [samarthhapse/sarthi#130]
1.add dark mode button from one page to another page
2.making the page dark
3.resizing the pages and fixing the margins

**Comment by samarthhapse** [comment]
@VaibhavYT can you contribute for this issue ?

**Comment by VaibhavYT** [comment]
OK

**Comment by samarthhapse** [comment]
Okay, I will provide you code and details tonight

**Comment by samarthhapse** [comment]
Details : 

you raised a recent PR recently , I merged it in temp and updates same in main. Now I have reverted the PR for temp branch.

1. Now your code is in main branch ( old home page )
2. And new Ui is in temp branch ( new home page )

your task is to merge these two page.

**Comment by samarthhapse** [comment]
![temp](https://github.com/samarthhapse/sarthi/assets/131296047/5ce56ba8-fe0e-45d4-944d-ca811575f1ea)

you will get this UI of home page in temp branch.
Keep that as it is , just add below image's section (from main branch UI ) in place of arrow of this image

**Comment by samarthhapse** [comment]
![main](https://github.com/samarthhapse/sarthi/assets/131296047/4defc6b1-87f2-4bd2-9509-ac4412cc9fef)

**Comment by samarthhapse** [comment]
finally convert complete page in dark mode and add dark/light mode button in navbar.

**Comment by samarthhapse** [comment]
after completion I will be adding level 3 tag for PR of this issue.

**Comment by VaibhavYT** [comment]
Hello, In temp branch there is no New UI . I have fetched the latest commit but still now new UI.

**Comment by samarthhapse** [comment]
New ui is I main branch, copy that one in temp

**Comment by samarthhapse** [comment]
Just a .imute

**Comment by samarthhapse** [comment]
clone this repo to get new code of home page only

https://github.com/Abhishek-465/sarthi.git

**Comment by samarthhapse** [comment]
Hello @VaibhavYT . Now recently I have updated temp, get complete code from there. And get code of only new home page from  https://github.com/Abhishek-465/sarthi.git . then as per above instructions make changes in temp only and raise PR on temp.

**Comment by VaibhavYT** [comment]
Still not showing new HomePage UI in temp branch.

**Comment by samarthhapse** [comment]
new one is here https://github.com/Abhishek-465/sarthi.git

take code of new from above repo

**Comment by samarthhapse** [comment]
them add that in temp branch's code

**Comment by VaibhavYT** [comment]
## Talk

which repo showing last commit was in last wee

![code-new](https://github.com/samarthhapse/sarthi/assets/78371075/1c741b1a-164e-4873-9f37-6ed0f79427f6)

**Comment by samarthhapse** [comment]
okay , just go through #126 => files changed => you will get the complete code there just update it in temp branch's code

**Comment by VaibhavYT** [comment]
Why sir only level 2 ?
Please make it level 3.
I had meged the code.
I will open PR.

**Comment by samarthhapse** [comment]
Okay @VaibhavYT , added level 3. Just make hurry and create .

**Comment by VaibhavYT** [comment]
I have created please have a look

**Comment by samarthhapse** [comment]
hello @VaibhavYT , I merged the PR , these are some corrections : 

1. toggle dark/light mode button is not present on navbar
2. on click of login button it direct on below page

**Comment by samarthhapse** [comment]
![Screenshot 2024-06-05 124259](https://github.com/samarthhapse/sarthi/assets/131296047/3ac4e8ed-f2db-492d-81f3-62ad3a8ff037)

just change the route

**Comment by samarthhapse** [comment]
Mistake : I asked to change the UI of home page only but here UI of complete app is changed ( home + dashboard + signup + signin )

Quick Suggestion : 

step 1 : clone prev branch
step 2 : just copy the code of home page from temp
step 3 : paste the copied code of step 2 in code of step 1 branch's code
step 4 : raise one more PR on temp

**Comment by VaibhavYT** [comment]
You want me add the dark mode in this branch and to change the login navigation?

**Comment by samarthhapse** [comment]
@VaibhavYT , for making things simple . I have added my code in temp branch. I have managed that route and added toggle button .

**Comment by samarthhapse** [comment]
now all you have to do is => Converting the whole website in dark mode and making it light on click of toggle button

**Comment by samarthhapse** [comment]
Now the task is simple. Just add dark mode s default and managing the dark/light mode.

**Comment by samarthhapse** [comment]
hello @VaibhavYT did you got it ? 
Or I have to elaborate more

**Comment by VaibhavYT** [comment]
Yes I will try to do it.

**Comment by samarthhapse** [comment]
yes , it is simple now . 

Just complete UI dark and manage that dak/light button

**Comment by samarthhapse** [comment]
@VaibhavYT completed ? pls do it today only

**Comment by VaibhavYT** [comment]
Sure I will try to complete it by today.

**Comment by samarthhapse** [comment]
Yes, please !

**Comment by VaibhavYT** [comment]
Last code is hard coded theme change. I am making the dark mode and light mode dynamic.

**Comment by samarthhapse** [comment]
okay !

**Comment by VaibhavYT** [comment]
## Talk
is it now good?

https://github.com/samarthhapse/sarthi/assets/78371075/1e995955-de5a-4c6c-bf17-509723802199

**Comment by VaibhavYT** [comment]
You may please give feedback . After that I will an PR, waiting for your reply since yesterday

**Comment by samarthhapse** [comment]
If it is working for all the pages  ( home page , student sign-in , student sign-up , expert sign-in , expert sign-up , student otp ,expert otp ). So you can definitely raise the PR

**Comment by VaibhavYT** [comment]
I had raised the PR kindly look into that

**Comment by samarthhapse** [comment]
@VaibhavYT just solve conflicts asap, I have further issues for you.

**Comment by VaibhavYT** [comment]
which issue?

**Comment by samarthhapse** [comment]
I will open today
