### ISSUE TITLE
React component for displaying an error page with a Lottie animation

### ISSUE THREAD

**Issue by jaebee2** [samarthhapse/sarthi#139]
**Improvement for the error handing **
Your React component for displaying an error page with a Lottie animation looks mostly correct. However, there are a few improvements you could make to ensure better readability and functionality. 
**To Reproduce**
1. Remove unnecessary commented code.
2. Fixed Positioning and Dimensions
3. Consistent Indentation
4. Combined Classes

**Expected behavior**
The refined version should provide a more consistent layout and ensure that both the button and the animation are centered properly on the error page.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by samarthhapse** [comment]
@jaebee2 I am assigning this issue to you. Complete it with perfection and raise PR on temp branch by 13 EOD.

**Comment by samarthhapse** [comment]
@jaebee2 completed ?

**Comment by samarthhapse** [comment]
added labels , assigned it . Even no updates ? are you working

**Comment by Jagpreet153** [comment]
> added labels , assigned it . Even no updates ? are you working

@samarthhapse This page already exists .
![Screenshot 2024-06-18 070537](https://github.com/samarthhapse/sarthi/assets/119691733/54caeaba-8855-4b5e-81e6-ce5eb6e4c211)
