### ISSUE TITLE
filtering experts from backend

### ISSUE THREAD

**Issue by samarthhapse** [samarthhapse/sarthi#140]

**Comment by Taufiq-Y** [comment]
Hi, Pls ellaborate your issue to resolve this.

**Comment by samarthhapse** [comment]
TASK : after student login he must get three sections to choose
1.Bug solving
2.Tech career assistance
3.Academic support
after selecting the section from above mentioned options , student must get list of all experts available in DB for the specific option

**Comment by jelly-afk** [comment]
hi, i would like to work on this

**Comment by samarthhapse** [comment]
@Taufiq-Y please reply fast.

**Comment by samarthhapse** [comment]
> TASK : after student login he must get three sections to choose 1.Bug solving 2.Tech career assistance 3.Academic support after selecting the section from above mentioned options , student must get list of all experts available in DB for the specific option


@Taufiq-Y this is the issue you have too resolve
