### ISSUE TITLE
Add logo and  make site Responsive

### ISSUE THREAD

**Issue by kavitameena108** [samarthhapse/sarthi#141]
Add a logo for site
Enhance the site using responsiveness.

I want to work on this issue please @samarthhapse assign me .

**Comment by kavitameena108** [comment]
also  add suitable label under gssoc'24.

**Comment by samarthhapse** [comment]
@kavitameena108 assigning this issue to you. Start working on it. Please try to complete by 13 EOD

**Comment by samarthhapse** [comment]
main task is making it completely responsive. If you manage to do so I will add level 2 after completion of task. 

Work on temp branch and make PR on temp branch only

**Comment by kavitameena108** [comment]
ok . I will do this.
