### ISSUE TITLE
Some text is not visible in light mode

### ISSUE THREAD

**Issue by NidhiTornekar** [samarthhapse/sarthi#142]
**Describe the bug**
In the student signup page, when in light mode , the lines "Create your account" and  "Already a registered student" are not visible since it is also in the same colour as the background

**To Reproduce**
1. Go to Login page
2. Click on Student as the profession
3. Click on signup, make sure the browser is in light mode
4. See error(Certain lines are not visible)

**Expected behavior**
The above lines should be visible, hence I can change the class in StudentSignup.jsx to make them appear in darker colour

**Screenshots**
This is in light mode, where certain lines are not visible
![ss11](https://github.com/samarthhapse/sarthi/assets/121748841/14539233-b722-404f-9f8f-72ee589c055a)
This is the same page in dark mode (where lines are visible)
![ss12](https://github.com/samarthhapse/sarthi/assets/121748841/6fbc7698-3edc-4388-b028-609be85e2898)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: Windows
 - Browser [e.g. chrome, safari]: Chrome
 - Version [e.g. 22]: Windows 10, Chrome version: 125.0.6422.142

**Additional context**
Please assign me this issue under GSSOC 2024

**Comment by samarthhapse** [comment]
@NidhiTornekar why closed the issue. Btw let it be closed , you can comment on #140 if you have experience in backend (node,express)

**Comment by divyansh-2005** [comment]
Hey, @samarthhapse I want to work on this issue.
Should I create a new issue ?

**Comment by samarthhapse** [comment]
@divyansh-2005 I will reach out to you within 2 days

**Comment by bheemajayashreee** [comment]
@samarthhapse Please assign this issue to me
