### ISSUE TITLE
Add link to Home in Navbar

### ISSUE THREAD

**Issue by divyansh-2005** [samarthhapse/sarthi#145]
**Describe the bug**
Nabar is missing link to Home.

**Expected behavior**
Link to Home page can be added in navbar

**Screenshots**
![image](https://github.com/samarthhapse/sarthi/assets/118552563/f4542080-4f05-4032-bffb-2d1fc0b3c10a)

**Comment by divyansh-2005** [comment]
Please assign me this task so that I can work on it as soon as possible under GSSOC'24.

**Comment by samarthhapse** [comment]
@divyansh-2005  just do it asap

**Comment by divyansh-2005** [comment]
@samarthhapse, can u assign this issue. So that I can work on it asap

**Comment by samarthhapse** [comment]
done
