### ISSUE TITLE
Text-color of Frequently asked questions in Dark mode

### ISSUE THREAD

**Issue by divyansh-2005** [samarthhapse/sarthi#146]
**Describe the bug**
Frequently asked questions are not visible in dark mode

**Expected behavior**
color of text can be changed to improve visiblity

**Screenshots**
Issue with text color:
![image](https://github.com/samarthhapse/sarthi/assets/118552563/054eb06b-98ff-472b-a772-8a204c990ed1)

**Comment by samarthhapse** [comment]
@divyansh-2005  it is very small issue , but okay , make it quickly

**Comment by divyansh-2005** [comment]
@samarthhapse, can u assign this issue. So that I can work on it asap

**Comment by samarthhapse** [comment]
done

**Comment by divyansh-2005** [comment]
will this be considered for GSSOC'24 ?

**Comment by samarthhapse** [comment]
sure man , that's why I am adding labels
