### ISSUE TITLE
Setting up basic backend and login/signup functionality

### ISSUE THREAD

**Issue by rikhiltaneja** [samarthhapse/sarthi#15]
## Description
Development of complete setup of Backend Server and Database.

The project currently does not have a backend server and a connect DB. So, I will setup both the things and make them ready to be connect with the frontend part of this project. I will also **deploy the server** to make it production ready. 
Other than the basic setup, I will also develop the **complete login/signup** functionality (backend). It will include all necessary things like **schema**(s), **validation** files + **middlewares**, **error handling**, **JWTs**, **profile customization**, etc.

_{By basic backend setup I mean, necessary things like Express App, Mongoose & MongoDB, Custom Error Class, Error Handling Middlewars, etc. will be developed}_

### Tech libraries/frameworks which I will use to accomplish the above mentioned task(s):
- ExpressJS
- NodeJS
- JWT
- MongoDB
- Mongoose
- Vercel

@samarthhapse  Please assign me this issue (under GSSOC'24). I will do my best to accomplish all the tasks mentioned above.
Looking forward to a positive response! 🙂

**Comment by spywolf2049** [comment]
Hello mentor , my  expertise and skills in web development could greatly contribute to the success of this endeavor. I believe that my insights and contributions would play a crucial role in creating a user-friendly and efficient authentication process for our users.

Here are some key features and functionalities I will add for the Login and Signup Page:

Secure user authentication with password hashing and encryption.
User-friendly interface with clear instructions and error handling.
Seamless integration with our existing database and backend services.
Customizable user profiles with options for personalization.
Implementation of best practices for data protection and privacy compliance.

Please assign me this issue under GSSOC'24.

**Comment by rawani123** [comment]
can you assig this issue to me ?
i just a basic idea what type of models you want in this?
and functionalitus in this project

**Comment by itssahillwhat** [comment]
Hey,

Hope you're doing well! I'm eager to dive into setting up the basic backend and implementing the login/signup functionality. I'm a GSSOC 24 Contributor. Could you please assign me the relevant issue so I can get started? Looking forward to tackling this!

**Comment by Jatingupta9120** [comment]
assign this issue to me

**Comment by rikhiltaneja** [comment]
@samarthhapse You have added the labels for this issue (raised by me). So, please assign it to me as well. 

Looking forward to a quick and positive response!

**Comment by souravupreti005** [comment]
assign this issue to me

**Comment by IkramBagban** [comment]
Hello @samarthhapse 

I am very interested in contributing to this project under GSSOC'24. I have a good understanding of the technologies mentioned (ExpressJS, NodeJS, MongoDB, etc.) and I am eager to apply my skills to develop the backend and login/signup functionality as described in issue #15.

Could you please assign this issue to me? I am looking forward to working on this and contributing to the project.

Thank you!

**Comment by Jish261203** [comment]
I am very excited in contributing to this project under GSSOC'24. @samarthhapse  can you please assign this to me

**Comment by Aman0413** [comment]
Please assign to me.

**Comment by Mandar007007** [comment]
Hello, I have great experience in building this functionality please assign it to me

**Comment by SanaAzeem512** [comment]
hello 
As a GSsoc'24 contributer , I would like to work on this issue. Could you kindly assign me to work on this issue?

**Comment by mutcherlarahulkumar** [comment]
I would like to the backend functionality of login/signup please assign me this task. I would like to work on it

**Comment by gyanendra-baghel** [comment]
Hello Sir, I want to build basic template of this project with login and signup functionalities with mongo db. 

@samarthhapse Could you please this task to me.

**Comment by Jhonsnowwwwww** [comment]
@samarthhapse 
 Hey,

Hope you're doing well! I'm eager to dive into setting up the basic backend and implementing the login/signup functionality. I'm a GSSOC 24 Contributor. Could you please assign me the relevant issue so I can get started? Looking forward to tackling this!

**Comment by samarthhapse** [comment]
Hello there , I am opening this issue again. Have a quick overview of backend code and if anyone is ready to design signup and login page according to that attributes then comment of #10.

**Comment by samarthhapse** [comment]
yes please , do checkout #10 read all comments for detailed info about task and make a PR. I will add labels to PR if it fulfills the needs

**Comment by samarthhapse** [comment]
comment below when if you have started working

**Comment by samarthhapse** [comment]
@gyanendra-baghel also comment here with the expected date of submission from your side

**Comment by samarthhapse** [comment]
Hello everyone there , comment on #20 if you are experienced in advanced react and tailwind and willing to work on same signup and login page to update the old simple one in to the super cool page with attention seeking animations and much more changes

**Comment by Sneha0019** [comment]
Hello, I have a very good experience in the backend and have done lot of work in backend development. I can do backend work of login and signup functionality and also will use validations using JWT web token as well as other react library. looking forward for your positive reply!

**Comment by Ankit389** [comment]
Hello sir 
I'm a GSSOC'24 contributor...i want to work on this issue please assign this task to me..i will complete this task with in one day and please assign label to it also

**Comment by ROKUMATE** [comment]
Hello,  i have the experience in building the login and signup controllers and models using the JWT tokens, and saving in the mongodb databse after using a hash function on it ... 
its same logic is used in one of mine projects that is been uploaded as a repo ...
so i kindly request u to assign this issue to me.
