### ISSUE TITLE
fix api endpoints

### ISSUE THREAD

**Issue by jelly-afk** [samarthhapse/sarthi#152]
api endpoints do not match in frontend and backend, fix all the api endpoints, fix the functions and update all the refrences

![Screenshot at 2024-06-13 20-38-38](https://github.com/samarthhapse/sarthi/assets/117983104/c45ade6d-a2f5-4e3b-a375-1648e7bc8ae7)
![Screenshot at 2024-06-13 20-39-12](https://github.com/samarthhapse/sarthi/assets/117983104/ae31125c-a18c-4c62-a7c7-7ee13ef65e51)

**Comment by jelly-afk** [comment]
i will resolve this issue

**Comment by samarthhapse** [comment]
@jelly-afk as I merged your previous PR , OTP for expert was not working . You can work to fix this and make PR. I am assigning this issue to you
