### ISSUE TITLE
text colours

### ISSUE THREAD

**Issue by jennifereunice** [samarthhapse/sarthi#157]
while login and signup the text that are entering is not visible its colours need to be changed such that the user should know what they are typing
![image](https://github.com/samarthhapse/sarthi/assets/105411915/fa2ab22f-9c4e-4396-9288-f37ff2da1588)

**Comment by samarthhapse** [comment]
@jennifereunice please wait till evening . If necessary I will assign it

**Comment by Bhushan-04** [comment]
assign this to me , if its okay for you !

**Comment by jennifereunice** [comment]
Have you checked

**Comment by samarthhapse** [comment]
yes, you can start. I am assigning. Try to raise PR by afternoon

**Comment by samarthhapse** [comment]
@Bhushan-04 if you are experienced in react and tailwind I have an another issue for you. Just comment below , I will asiign

**Comment by jennifereunice** [comment]
> @jennifereunice yes, you can start. I am assigning. Try to raise PR by afternoon

please assign me the label

**Comment by samarthhapse** [comment]
@jennifereunice assigned label , try to complete by evening

**Comment by jennifereunice** [comment]
> @Bhushan-04 if you are experienced in react and tailwind I have an another issue for you. Just comment below , I will assign

if he is not interested please assign that issue to me i am good at react

**Comment by samarthhapse** [comment]
> > @Bhushan-04 if you are experienced in react and tailwind I have an another issue for you. Just comment below , I will assign
> 
> if he is not interested please assign that issue to me i am good at react

sure

**Comment by Aradhyajha** [comment]
Hii @samarthhapse 
![text color](https://github.com/samarthhapse/sarthi/assets/130289875/b293e78f-18e9-4fbb-9060-b270b78e6afa)
The issue involves enhancing the web application by adding a responsive navigation bar (navbar) and interactive UI elements, including designing a navbar with links to Home, About, Services, and Contact sections, ensuring it is responsive and mobile-friendly, implementing smooth scrolling and dynamic content display using JavaScript, setting a default section to show on page load, utilizing a CSS framework like Bootstrap for improved design and responsiveness, adding basic accessibility features for usability by all users, and specifying text color changes to enhance visual appeal and readability of the navbar and content sections.

**Comment by Ankit389** [comment]
Hi  if no one is yet assigned I would like to take on this issue.
Proposed solution : Change the corresponding CSS style to make the redirect text colours more visible.
ETA: 1-2 day.

![imege](https://github.com/samarthhapse/sarthi/assets/163544230/7d05c818-43ea-435d-b992-fa3ffcc8c3f9)


I can solve this problem I have worked on this before
while login and signup the text that are entering is not visible its colours need to be changed such that the user should know what they are typing

**Comment by jennifereunice** [comment]
> > > @Bhushan-04 if you are experienced in react and tailwind I have an another issue for you. Just comment below , I will assign
> > 
> > 
> > if he is not interested please assign that issue to me i am good at react
> 
> sure

u said u have some issue will u assign that to me

**Comment by samarthhapse** [comment]
@jennifereunice do you have experience in three.js / advanced react

**Comment by Bhushan-04** [comment]
> @Bhushan-04 if you are experienced in react and tailwind I have an another issue for you. Just comment below , I will assign

sure , let me know !

**Comment by modest-azad** [comment]
In simple, It has color contrast issue.
As an UI Designer and frontend developer, I can easily handle this while maintaining your current site theme.

**Comment by modest-azad** [comment]
> @Bhushan-04 if you are experienced in react and tailwind I have an another issue for you. Just comment below , I will assign

Yes, I also have experience in UI/UX Designing and Frontend Development (React.js, Tailwind CSS, Next.js and NextUI)....
