### ISSUE TITLE
Improving the hovering effect of navbar.

### ISSUE THREAD

**Issue by Khushipawar37** [samarthhapse/sarthi#160]
When the navbar items are hovered over, their visibility reduces making the user difficult to read the contents clearly. 
When the feature and resources drop-down is clicked, the text is not even visible clearly due too similar background and font color of the text. 

Solution :- 

I would update the font-color and change it accordingly to improve the visibility keeping in mind the UI design of the website. 

![Screenshot 2024-06-14 192743](https://github.com/samarthhapse/sarthi/assets/164056757/9c9ba5bb-1fd6-45da-a226-729b5e1358bc)

**Comment by samarthhapse** [comment]
@Khushipawar37 I am assigning it to you , try to complete asap

**Comment by Khushipawar37** [comment]
@samarthhapse, I will complete it by 17th. Kindly assign the Gssoc'24 label to it with level.

**Comment by samarthhapse** [comment]
minor issue, must be submitted by tonight
