### ISSUE TITLE
New Logo and fix the size of logo.

### ISSUE THREAD

**Issue by divyansh-2005** [samarthhapse/sarthi#163]
Current logo is not of proper size because of logo the navbar is scrolling.
Logo can be changed also background of logo must be removed.

Here are some logo ideas
![image](https://github.com/samarthhapse/sarthi/assets/118552563/e7911839-4982-4b49-aa18-3523ac30bf84)

**Comment by samarthhapse** [comment]
sure , do it

**Comment by samarthhapse** [comment]
just remove bg and resize the image

**Comment by divyansh-2005** [comment]
Can u assign this issue.

**Comment by samarthhapse** [comment]
do not add old logo, create new one. Extra bold font, dark blue color name "sarthi"

**Comment by samarthhapse** [comment]
![Screenshot 2024-06-15 153209](https://github.com/samarthhapse/sarthi/assets/131296047/1d261a57-acc0-4ed2-832d-7b1b0fa8dd58)


just like this only name "sarthi" & dark blue colour

**Comment by divyansh-2005** [comment]
okay

**Comment by divyansh-2005** [comment]
light mode:
![image](https://github.com/samarthhapse/sarthi/assets/118552563/7924e566-cb4d-4778-ad68-38e54d923579)
Dark mode:
![image](https://github.com/samarthhapse/sarthi/assets/118552563/72d243c7-2a63-41bc-9b32-d890a89431b1)

will this work? As dark blue color is not visible in dark mode

**Comment by divyansh-2005** [comment]
please add labels
