### ISSUE TITLE
adding default dark mode & changing UI of expert signup page 

### ISSUE THREAD

**Issue by samarthhapse** [samarthhapse/sarthi#164]
task 1 : default dark mode of whole website

task 2 : make expert signup page similar to student signup page

NOTE : do not make input entries/logical changes (just change design)

![Screenshot 2024-06-15 061910](https://github.com/samarthhapse/sarthi/assets/131296047/c69dcc6e-0387-4a1b-94e8-f11d2febc598)

**Comment by samarthhapse** [comment]
@VaibhavYT If you are willing to work comment below

**Comment by VaibhavYT** [comment]
Sure 👍🏻

**Comment by samarthhapse** [comment]
try to submit by evening

**Comment by VaibhavYT** [comment]
Please add gssoc label and good level this will help me also.

**Comment by VaibhavYT** [comment]
I had coded this please make label and level then I will raise an PR.

**Comment by samarthhapse** [comment]
added labels

**Comment by samarthhapse** [comment]
please make hurrry @VaibhavYT

**Comment by samarthhapse** [comment]
Hello @VaibhavYT , I have an issue for you #174 . Pls comment there asap, I wanted it today only (with very basic UI)

**Comment by VaibhavYT** [comment]
Ok

**Comment by samarthhapse** [comment]
@VaibhavYT pls wait for 2 days . Multipe issues with higher levels as coming for you !

**Comment by VaibhavYT** [comment]
Sure waiting

**Comment by samarthhapse** [comment]
Hello @VaibhavYT !

**Comment by samarthhapse** [comment]
@VaibhavYT . now backend part is completed , now it's time to gear up backend

**Comment by VaibhavYT** [comment]
Hello , I thought you will not come back

**Comment by VaibhavYT** [comment]
Raise issue / feature , you want to add

**Comment by samarthhapse** [comment]
@VaibhavYT , have you forked the current code form temp-af barnch. Pls start frontend and backend once. If facing some issue let me know now

**Comment by samarthhapse** [comment]
@VaibhavYT I will help

**Comment by VaibhavYT** [comment]
Okay sure

**Comment by samarthhapse** [comment]
started ? any problem ?

**Comment by VaibhavYT** [comment]
working fine frontend

**Comment by VaibhavYT** [comment]
server is not running but when I try with node index.js

**Comment by VaibhavYT** [comment]
hello

**Comment by samarthhapse** [comment]
Just mailed you my personal email file. Justa add it in server folder

**Comment by VaibhavYT** [comment]
okay

**Comment by samarthhapse** [comment]
Please update immediately

**Comment by VaibhavYT** [comment]
id scheme, expected connection string to start with "mongodb://" or "mongodb+srv://"
    at new ConnectionString (V:\Web Development\GSOC\sarthi\sarthi\server\node_modules\mongodb-connection-string-url\lib\index.js:86:19)
    at parseOptions (V:\Web Development\GSOC\sarthi\sarthi\server\node_modules\mongoose\node_modules\mongodb\lib\connection_string.js:192:17)
    at new MongoClient (V:\Web Development\GSOC\sarthi\sarthi\server\node_modules\mongoose\node_modules\mongodb\lib\mongo_client.js:52:63)
    at NativeConnection.createClient (V:\Web Development\GSOC\sarthi\sarthi\server\node_modules\mongoose\lib\drivers\node-mongodb-native\connection.js:293:14)
    at NativeConnection.openUri (V:\Web Development\GSOC\sarthi\sarthi\server\node_modules\mongoose\lib\connection.js:801:34)
    at Mongoose.connect (V:\Web Development\GSOC\sarthi\sarthi\server\node_modules\mongoose\lib\mongoose.js:414:15)
    at connectDB (file:///V:/Web%20Development/GSOC/sarthi/sarthi/server/config/connection.js:5:20)
    at Server.<anonymous> (file:///V:/Web%20Development/GSOC/sarthi/sarthi/server/index.js:31:3)
    at Object.onceWrapper (node:events:633:28)
    at Server.emit (node:events:531:35)

**Comment by VaibhavYT** [comment]
it is unable to load the env file mogo uri

**Comment by VaibhavYT** [comment]
Now working 😁✅

**Comment by samarthhapse** [comment]
> Now working 😁✅

Great 👍🏻

**Comment by samarthhapse** [comment]
Now I am opening issues

**Comment by VaibhavYT** [comment]
SURE

**Comment by samarthhapse** [comment]
Pls start on issue 211

**Comment by samarthhapse** [comment]
@VaibhavYT Pls comment there.  I will assign

**Comment by VaibhavYT** [comment]
okay

**Comment by VaibhavYT** [comment]
assign me that I will make website responsive

**Comment by samarthhapse** [comment]
@VaibhavYT we will wait far 2 days for issue 211, till then comment on 214, I am assigning it to you

**Comment by VaibhavYT** [comment]
sure
