### ISSUE TITLE
authorizing experts 

### ISSUE THREAD

**Issue by samarthhapse** [samarthhapse/sarthi#172]
Purpose of issue => to verify the expert's profile before getting saved in DB

when expert submits signup form, website owner should get email. Only if website owner authorizes the expert from his side then the expert's data should get saved in DB.

**Comment by ayann07** [comment]
I could give it a try, since it is quite difficult to implement, so I might give up in between and let you know, but in the meanwhile I would like to atleast give a try. So assign me

**Comment by samarthhapse** [comment]
okay , please start and keep updating here. I am assigning

**Comment by samarthhapse** [comment]
Hello @ayann07 , there is some issue regarding otp.We were discussing that in issue no => 174. Can you try to resolve it and raise PR. I will assign one new issue to you. If you manage to do so.

**Comment by samarthhapse** [comment]
@ayann07 pls update ?

**Comment by samarthhapse** [comment]
@ayann07 have you got the basic idea to resolve this ?

**Comment by samarthhapse** [comment]
@ayann07 pls keep updating daily, It ensures that any feature is not getting lagged

**Comment by samarthhapse** [comment]
@ayann07 , again the same thing happening. You might be working on resolving the issue. It does not matter hoe much time it take. Just updates need to be shared here.

**Comment by ayann07** [comment]
I am working on it

**Comment by samarthhapse** [comment]
Hello @ayann07 completed ?

**Comment by samarthhapse** [comment]
@ayann07 pls share your updates

**Comment by samarthhapse** [comment]
@ayann07 pls update immedietly

**Comment by samarthhapse** [comment]
@ayann07

**Comment by samarthhapse** [comment]
@ayann07

**Comment by ayann07** [comment]
I'll take 3-4 days more

**Comment by samarthhapse** [comment]
@ayann07 okay , but just finish it completely in 3-4 days.

**Comment by samarthhapse** [comment]
@ayann07 pls try to complete asap. I have one more level3 issue for you

**Comment by ayann07** [comment]
Sure bro, give me few more days, most of the part is done

**Comment by samarthhapse** [comment]
great !

**Comment by samarthhapse** [comment]
Hello @ayann07 , is it completed

**Comment by samarthhapse** [comment]
Hello @ayann07 , it has been more 5 days , completed ?

**Comment by samarthhapse** [comment]
@ayann07 , raise PR asap ?

**Comment by samarthhapse** [comment]
@ayann07 , I have some more level3 issues for you

**Comment by samarthhapse** [comment]
@ayann07 why not replying

**Comment by samarthhapse** [comment]
@ayann07 pls do fast

**Comment by samarthhapse** [comment]
@ayann07 it is so much delayed

**Comment by samarthhapse** [comment]
@ayann07 , when raising the PR

**Comment by samarthhapse** [comment]
@ayann07 hurry up

**Comment by samarthhapse** [comment]
@ayann07

**Comment by samarthhapse** [comment]
@ayann07

**Comment by samarthhapse** [comment]
@ayann07

**Comment by samarthhapse** [comment]
> Sure bro, give me few more days, most of the part is done

@ayann07 , as most of part was done last week only. Why you aren't raising PR yet ?

**Comment by samarthhapse** [comment]
@ayann07 , so much time is getting wasted

**Comment by samarthhapse** [comment]
Hello @ayann07 , what's update

**Comment by samarthhapse** [comment]
@ayann07 just tell , if you are not working

**Comment by ayann07** [comment]
Sorry I am not working

**Comment by samarthhapse** [comment]
@ayann07 , if you are not working , pls tell immediately pls. I can assign to someone else

**Comment by samarthhapse** [comment]
okay @ayann07 non problem , available to work on any another one ?
