### ISSUE TITLE
Adding an eye button in the password field

### ISSUE THREAD

**Issue by pani2004** [samarthhapse/sarthi#176]
I can add a eye button for pw visibility in the login page
![Screenshot 2024-06-17 220719](https://github.com/samarthhapse/sarthi/assets/154724111/f7c8e282-15d3-4d49-af98-6370f86c452a)

**Comment by pani2004** [comment]
@samarthhapse Can I work on this?

**Comment by KavyaBS123** [comment]
Hey @samarthhapse I am VSoC contributor can you please assign this issue to me I would like to work on it!

**Comment by modest-azad** [comment]
I can easily implement it by changing Input type dynamically by clicking on eye icon placed in inside input field. 
![Uploading azad_ type password.jpg…]()

**Comment by samarthhapse** [comment]
@pani2004 , pls start working on this issue and raise PR asap

**Comment by samarthhapse** [comment]
@KavyaBS123 , have you worked on video meet bot in MERN stack ?

**Comment by KavyaBS123** [comment]
Hey @samarthhapse yup!
I have worked on it quite a few times

**Comment by samarthhapse** [comment]
okay @KavyaBS123 , comment on #89 . If you can complete it within 4 to 5 days

**Comment by samarthhapse** [comment]
@pani2004 please comment once you have started resolving this issue

**Comment by KavyaBS123** [comment]
> okay @KavyaBS123 , comment on #89 . If you can complete it within 4 to 5 days

Sure sure I am on it!

**Comment by pani2004** [comment]
@samarthhapse Yess I am on it

**Comment by samarthhapse** [comment]
Okay

**Comment by pani2004** [comment]
@samarthhapse pls assign me

**Comment by samarthhapse** [comment]
Assigned

**Comment by samarthhapse** [comment]
@pani2004 you added it only for signin. Pls add it for signup also

**Comment by pani2004** [comment]
ok @samarthhapse

**Comment by pani2004** [comment]
@samarthhapse should I make a new PR for this?

**Comment by samarthhapse** [comment]
Yesss

**Comment by pani2004** [comment]
@samarthhapse check the PR
