### ISSUE TITLE
step 2

### ISSUE THREAD

**Issue by samarthhapse** [samarthhapse/sarthi#177]

**Comment by Aradhyajha** [comment]
@samarthhapse , please assign this issue #177 to me , i will complete this as soon as possible
To add an "Expert Home" in this project, create a new component or page for the "Expert Home" section using the framework in use (e.g., React, Vue, Angular). Integrate this component into the existing project by updating the router configuration to include a new route pointing to the "Expert Home" component. Ensure the navigation menu is updated to include a link to this new section. Test the new component for functionality and compatibility with the existing project. Once complete, submit a pull request with a detailed description of the addition, referencing the issue number related to the "Expert Home" feature.

**Comment by jelly-afk** [comment]
i was supposed to do this, so you can try it ig

**Comment by samarthhapse** [comment]
@jelly-afk I have always , go through the profolios before assigning

**Comment by samarthhapse** [comment]
@jelly-afk do not assign you task to any another contributors. It just consumes 1 to 2 more days of project

**Comment by samarthhapse** [comment]
@jelly-afk , do not worry , I will surely assign any another task to you. I will reach out to you in such case

**Comment by samarthhapse** [comment]
main thing is new contributors are not aware of how old features are interconnected with each other.

**Comment by Aradhyajha** [comment]
Okay sir.. thank you

**Comment by samarthhapse** [comment]
do not worry. If I have any issue for you. I will surely reach out to you

**Comment by samarthhapse** [comment]
@jelly-afk pls try to complete this asap

**Comment by samarthhapse** [comment]
completed @jelly-afk

**Comment by jelly-afk** [comment]
No power here since two days, so can't use pc

**Comment by samarthhapse** [comment]
@jelly-afk , what is expected submissiondate from your side.

**Comment by samarthhapse** [comment]
@jelly-afk pls try to do on priority

**Comment by jelly-afk** [comment]
I can't do anything right now, it's not in my hands

**Comment by samarthhapse** [comment]
@jelly-afk , okay. But I am not assigning this issue to anyone else

**Comment by samarthhapse** [comment]
@jelly-afk , so please confirm you are completing this issue asap when possible

**Comment by jelly-afk** [comment]
Alright, i will complete it as soon as power is back

**Comment by samarthhapse** [comment]
great ! btw have you participate in VSoC'24

**Comment by jelly-afk** [comment]
Yes

**Comment by samarthhapse** [comment]
okay

**Comment by samarthhapse** [comment]
@jelly-afk , power back ?

**Comment by samarthhapse** [comment]
@jelly-afk , added labels of VSoC'24 to all your current and previous PR's . Also added BONUS points for 2 of them
