### ISSUE TITLE
Privacy policy page

### ISSUE THREAD

**Issue by Jagpreet153** [samarthhapse/sarthi#178]
I would like to add a privacy policy page . It would be completely responsive .
![Screenshot 2024-06-18 070933](https://github.com/samarthhapse/sarthi/assets/119691733/4ad7a5bd-0ccd-4176-a38f-35349ad9535b)

**Comment by samarthhapse** [comment]
@Jagpreet153 can you resolve issue no.174

**Comment by samarthhapse** [comment]
@Jagpreet153 pls comment if you can , it is required on urgent basis , by today EOD

**Comment by Jagpreet153** [comment]
@samarthhapse This otp error was faced by me also in #114 .

**Comment by samarthhapse** [comment]
It was resolved that time. Can you try this time

**Comment by Jagpreet153** [comment]
@samarthhapse Give your discord it is easy to discuss there

**Comment by samarthhapse** [comment]
sama1595

**Comment by samarthhapse** [comment]
@Jagpreet153 , why so inactive , I haven' recieved anything on diascord

**Comment by samarthhapse** [comment]
@Jagpreet153 project is already geting delayed, such inactiveness again causes time to waste in vey small features

**Comment by Jagpreet153** [comment]
@samarthhapse I cannot understand otp generation code . If you want kindly assign me this issue which I have opened #178

**Comment by samarthhapse** [comment]
@Jagpreet153 , okay . I will guide. Just tell me , If I assign you the task to create chat functionality (level 3 issue) . Student and expert should be able to chat between each other. Can you raise PR by today EOD

**Comment by Jagpreet153** [comment]
> @Jagpreet153 , okay . I will guide. Just tell me , If I assign you the task to create chat functionality (level 3 issue) . Student and expert should be able to chat between each other. Can you raise PR by today EOD

Web Sockets will be used for chat functionality but I have not worked with this tech stack before .

**Comment by samarthhapse** [comment]
okay

**Comment by samarthhapse** [comment]
@Jagpreet153 , can you work on integrating google meet feature in this app

**Comment by Jagpreet153** [comment]
> @Jagpreet153 , can you work on integrating google meet feature in this app

Ok . How much time ?
