### ISSUE TITLE
A simple online whiteboard for online meetings

### ISSUE THREAD

**Issue by samarthhapse** [samarthhapse/sarthi#183]

**Comment by Ar7109** [comment]
@samarthhapse  Assign this to me under gssoc 2024

**Comment by samarthhapse** [comment]
Hello @Ar7109 , This issue is actually being worked on anywhere else.

Can you work on creating a chat feature. Backend in node and express is already added. You just need to create frontend in React.js and connect it with backend

**Comment by nishant0708** [comment]
hey @samarthhapse assign it to me i will make that

**Comment by samarthhapse** [comment]
> Hello @Ar7109 , This issue is actually being worked on anywhere else.
> 
> Can you work on creating a chat feature. Backend in node and express is already added. You just need to create frontend in React.js and connect it with backend

@Ar7109 pls reply on this

**Comment by samarthhapse** [comment]
@nishant0708 , you can start working on this issue

**Comment by Ar7109** [comment]
> > Hello @Ar7109 , This issue is actually being worked on anywhere else.
> > Can you work on creating a chat feature. Backend in node and express is already added. You just need to create frontend in React.js and connect it with backend
> 
> @Ar7109 pls reply on this

Ok

**Comment by samarthhapse** [comment]
> > > Hello @Ar7109 , This issue is actually being worked on anywhere else.
> > > Can you work on creating a chat feature. Backend in node and express is already added. You just need to create frontend in React.js and connect it with backend
> > 
> > 
> > @Ar7109 pls reply on this
> 
> Ok

I will assign you within 2 days. Pls wait !

**Comment by samarthhapse** [comment]
@nishant0708 , pls reply fast

**Comment by samarthhapse** [comment]
@nishant0708 have you started working on this issue

**Comment by nishant0708** [comment]
No but I will complete it by tomorrow currently I am in office

**Comment by nishant0708** [comment]
> Hello @Ar7109 , This issue is actually being worked on anywhere else.
> 
> Can you work on creating a chat feature. Backend in node and express is already added. You just need to create frontend in React.js and connect it with backend

You need this right?

**Comment by samarthhapse** [comment]
@nishant0708 okay no problem, I am assigning this to you

**Comment by samarthhapse** [comment]
> > Hello @Ar7109 , This issue is actually being worked on anywhere else.
> > Can you work on creating a chat feature. Backend in node and express is already added. You just need to create frontend in React.js and connect it with backend
> 
> You need this right?

This is another one. I wanted "online meetings functionality". If you fix this meetings one properly. I will assign you chat one also

**Comment by nishant0708** [comment]
Okay can you share me what features it will have like whiteboard we see in zoom meets like that right

**Comment by samarthhapse** [comment]
@nishant0708 ,

![Screenshot 2024-06-23 175219](https://github.com/samarthhapse/sarthi/assets/131296047/d9523a31-2dde-4dc5-802e-da3b52f82ba3)

Description  :
you are expected to create a button on this page, which will have the feature to conduct the meet between student and the expert

reference => https://github.com/0x5eba/Video-Meeting

**Comment by nishant0708** [comment]
Okay got it .

**Comment by samarthhapse** [comment]
@nishant0708 , done with it ?

**Comment by samarthhapse** [comment]
@nishant0708 raise PR asap.

**Comment by nishant0708** [comment]
Bro actually the video call is working fine but I need to update it so that user when click on join meeting the expert should get notification when he click on notification he should also able to join that call just working on that .. trying my best should get done by tomorrow.. sorry for the delay

**Comment by samarthhapse** [comment]
@nishant0708 no problem. Keep going. Just raise PR asap

**Comment by samarthhapse** [comment]
@nishant0708 , completed it ?

**Comment by samarthhapse** [comment]
@nishant0708 , pls raise PR by today EOD

**Comment by samarthhapse** [comment]
![Screenshot 2024-07-06 120301](https://github.com/samarthhapse/sarthi/assets/131296047/74978d39-804c-49bf-ba4f-3120c8e8e6cc)

@nishant0708 , add button on this page

**Comment by samarthhapse** [comment]
@nishant0708 , it has been s long

**Comment by samarthhapse** [comment]
@nishant0708 , pls inform about what's going on for this issue

**Comment by samarthhapse** [comment]
@nishant0708 , raise PR asap. Just comment below when can you raise PR

**Comment by samarthhapse** [comment]
@nishant0708, should I remove you as assignee for this issue

**Comment by samarthhapse** [comment]
@nishant0708 , pls reply today itself, If you don't want ot work pls let know. Whatever the decision is just tell

**Comment by samarthhapse** [comment]
@nishant0708 , unassigned. You can comment later when you will be available.
