### ISSUE TITLE
Year needs to update dynamically in footer

### ISSUE THREAD

**Issue by kapilG0** [samarthhapse/sarthi#189]
**Describe the bug**
![image](https://github.com/samarthhapse/sarthi/assets/59639410/b534bf98-99d6-4360-9a05-1942c1dedb76)

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/samarthhapse/sarthi/assets/59639410/b89a6653-e81a-46d2-adef-834c92fcf2d8)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kapilG0** [comment]
Hello @samarthhapse please assign this issue to me under gssoc 24

**Comment by samarthhapse** [comment]
@kapilG0 actually this issue is not planned. Let us keep this issue asied. Please do comment below if you have experience in MERN stack development.
