### ISSUE TITLE
Adding respective icons to the navbar

### ISSUE THREAD

**Issue by harshmishra19** [samarthhapse/sarthi#19]
The current navbar lacks icons, which impacts its visual appeal and usability. Users might find it less engaging and intuitive to navigate through the website without visual cues provided by icons
I propose adding respective icons to the navbar to enhance its visual appeal and improve user navigation experience. These icons will align with the theme of the website and provide users with clear visual cues for each navigation option

for example

![Screenshot 2024-05-11 080754](https://github.com/samarthhapse/sarthi/assets/115486960/835ec44e-83f0-4806-a97a-fa2fce35e448)

Could you please assign me this issue under GSSOC 24

**Comment by aditya7483thakur** [comment]
Hello Sir ! Please assign this issue to me

**Comment by BagchiShreya** [comment]
Hi @samarthhapse 
I as a GSSoC'24 contributor would like to contribute to this issue. It would be great if you assign this issue to me and allow me to work on this project.

**Comment by anshdeep0504** [comment]
Hey, allow me to work on this under GSSOC' 2024
