### ISSUE TITLE
Create A Student Profile Page

### ISSUE THREAD

**Issue by ROKUMATE** [samarthhapse/sarthi#190]
A page from which the student will see his own profile and can also edit it

**Comment by ROKUMATE** [comment]
Sir, I would like u to assign mee this issue ... 
labelling a tag for gssoc and respective Level according to it u consider ... 

its the issue I mentioned in the #128 Issue of google auth

**Comment by samarthhapse** [comment]
Actually this issue is already done. @ROKUMATE , pls comment below if you have experience in backend/MERN development . I will assign much better issues to you with level 3.

**Comment by ROKUMATE** [comment]
@samarthhapse sure sir i have the experience and will be ok to qork on level 3 issue

**Comment by samarthhapse** [comment]
@ROKUMATE okay , I will assign any new issue to you within next 2 days
