### ISSUE TITLE
Adding Animation 

### ISSUE THREAD

**Issue by harshmishra19** [samarthhapse/sarthi#20]
- Your landing page already looks fantastic, but incorporating animations could make it even more captivating. With my experience in this area, I'm eager to contribute to this enhancement. 
- If you could assign me this task under GSSOC24, I would be thrilled to work on it. Thank you for considering my offer to improve Vite's appeal!

**Comment by Priyuan** [comment]
SOME ANIMATIONS NEED TO BE ADDED TO MAKE IT MORE APPEALING .I AM EAGER TO CONTRIBUTE IN THIS ARENA.

**Comment by namandude** [comment]
I would  like to add on my animation skills in this area to you project . Please assign it to me . 
Thank You!

**Comment by KashishRathore** [comment]
I would like to add more features in the Website
Can used more features through Tailwind Css and Bootstrap
Please Assign this task to me @samarthhapse

**Comment by TheNikhilRaj** [comment]
I would like to work on this issue , please assign this to me.
@samarthhapse

**Comment by K-21** [comment]
@harshmishra19 can you please assign this to me GSSOC'24

**Comment by akilesh1706** [comment]
@harshmishra19 Can you assign it to me as part of gssoc'24

**Comment by samarthhapse** [comment]
Hello everyone there #90  if you are experienced in advanced react and tailwind and willing to work on creating a cool profile page

**Comment by samarthhapse** [comment]
@harshmishra19 , @K-21 , @KashishRathore , @namandude , @akilesh1706 , @TheNikhilRaj I s anyone willing to work on this animation issue , comment on #91

**Comment by TheNikhilRaj** [comment]
Yes i am willing to work on this animation issue ? comment on #91.
Please assign me!

**Comment by samarthhapse** [comment]
@harshmishra19 , @KashishRathore have anyone worked on chat functionality integration in MERN stack
