### ISSUE TITLE
 Add Signup and Login Functionality with Google and GitHub

### ISSUE THREAD

**Issue by RithikaSundaram** [samarthhapse/sarthi#200]
We propose to enhance the Sarthi platform by adding signup and login functionalities using Google and GitHub accounts. This feature will streamline the onboarding process for new users and simplify authentication for existing users. By integrating the Google Sign-In API and GitHub OAuth, users can effortlessly authenticate with their existing accounts, eliminating the need to create and remember new credentials. This functionality will include "Continue with Google" and "Continue with GitHub" buttons on the signup and login pages. User profile information, such as name, email, and profile picture, will be securely retrieved and stored. This addition aims to improve user experience and ensure secure and efficient authentication.

**Comment by RithikaSundaram** [comment]
I am very much interested on working on this issue. Please assign it to me.

**Comment by samarthhapse** [comment]
@RithikaSundaram this issue is already completed. I will surely inform you , if any further issue is getting raised

**Comment by RithikaSundaram** [comment]
If I complete this task . Whether it will added on GSSOC'24
