### ISSUE TITLE
Payment gateway integration

### ISSUE THREAD

**Issue by samarthhapse** [samarthhapse/sarthi#201]

**Comment by aayushdhiman01** [comment]
@samarthhapse i would like to work on this issue , i am a vsoc contributor.

**Comment by Ankit389** [comment]
Hello sir
I'm a GSSOC'24 contributor...i want to work on this issue please assign this task to me..i will complete this task with in one day and please assign

**Comment by samarthhapse** [comment]
@Ankit389 assigning it to you.

**Comment by samarthhapse** [comment]
@Ankit389 try to raise PR by today only

**Comment by samarthhapse** [comment]
![Screenshot 2024-06-23 175219](https://github.com/samarthhapse/sarthi/assets/131296047/5533810d-7dfa-4b90-a557-477c87f0779d)

add a button ( Pay ) on this page to redirect on your gateway

**Comment by samarthhapse** [comment]
@Ankit389 , expert will add their mobile no. while signup , they should reciee the payments on that mobile number

**Comment by Ankit389** [comment]
ok  Sir

**Comment by Ankit389** [comment]
Sir, , there is multiple error in the project, there is an error in singup flie , it is taking time for me to fix it.

**Comment by samarthhapse** [comment]
@Ankit389 , pls fork code form temp-af branch. It has no errors

**Comment by samarthhapse** [comment]
@Ankit389 , started ?

**Comment by samarthhapse** [comment]
@Ankit389 , completed it ?

**Comment by samarthhapse** [comment]
@Ankit389 , what's problem

**Comment by samarthhapse** [comment]
@Ankit389 , whatever the problem is just tell

**Comment by samarthhapse** [comment]
@Ankit389 , I think you aren't working right. Pls inform me if you are not willing to work . I will assign  issue to someone else

**Comment by samarthhapse** [comment]
@Ankit389 ,pls inform immediately

**Comment by samarthhapse** [comment]
@Ankit389 , unassigning from this issue bcs of inactiveness, if you are willing to work on frontend (react.js) pls comment below
