### ISSUE TITLE
Responsiveness in for the smaller width 

### ISSUE THREAD

**Issue by upsaurav12** [samarthhapse/sarthi#202]
**Describe the bug**
Currently the main page is not responsive such as ``navbar`` is overflowing when the width is smaller that is result in unresponsiveness in the main page 
![image](https://github.com/samarthhapse/sarthi/assets/116784047/c3eef99b-e022-431f-beb7-14cce34255df)
![image](https://github.com/samarthhapse/sarthi/assets/116784047/16f5556e-b13a-4224-853a-5502bde5e74a)
in this image the page is having extra width in the page 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by upsaurav12** [comment]
HI I want to work in this issue pls assign me this issue

**Comment by samarthhapse** [comment]
@upsaurav12 Assigning to you , I will comment here tomorrow and then only you can start

**Comment by upsaurav12** [comment]
i am still waiting for @samarthhapse response
