### ISSUE TITLE
Landing page UI

### ISSUE THREAD

**Issue by codershrutik** [samarthhapse/sarthi#21]
The landing page of a website is very important as it gives the user a first impression of your website. the first impression of a website has to be dynamic and interactive. Therefore, the UX of the landing page has to be stellar.

The proposed landing page is given in the image.
![Sarthi landing page](https://github.com/samarthhapse/sarthi/assets/72141758/fafb49dd-1d3b-4b0c-b095-ffdfd08f8e42)
I am capable of designing as well as coding such a landing page. Please assign this issue to em as part of GSSOC'24.

**Comment by samarthhapse** [comment]
@codershrutik if I provide you with the UI design of landing page , will you be able to get it done.

**Comment by codershrutik** [comment]
@codershrutik Yes, I assure you I get it done

**Comment by mtg718** [comment]
@samarthhapse please assign this issue to me under GSSoc'24.
