### ISSUE TITLE
Responsiveness for all pages.

### ISSUE THREAD

**Issue by pahuja-sahil** [samarthhapse/sarthi#211]
I would like to make the website more responsive and properly alligned for small screen as the current layout for small screen is overlapping a bit as you can see in the image below:

![image](https://github.com/samarthhapse/sarthi/assets/140882358/841d8eae-5cff-4013-9a8d-50aa8d44726b)

![image](https://github.com/samarthhapse/sarthi/assets/140882358/0291386b-dbd5-4053-a004-74ab76e49bec)

![image](https://github.com/samarthhapse/sarthi/assets/140882358/d01f83d6-8cc5-4f17-ab2d-f595170ba618)

@samarthhapse kindly assign this issue to me under gssoc 24.
Thank you.

**Comment by samarthhapse** [comment]
@pahuja-sahil , haven't you signed in.

**Comment by samarthhapse** [comment]
@pahuja-sahil ,pls try to sign in as student and expert and check all pages till send and make all of them responsive for mobile only

**Comment by samarthhapse** [comment]
@pahuja-sahil , after this raise PR asap. I am assigning it to you

**Comment by pahuja-sahil** [comment]
@samarthhapse  got it . In the mean time i request you to assign this issue a level as well as a gssoc title .
thank you.

**Comment by pahuja-sahil** [comment]
one more thing should i add a hamburger for the nav bar for small screen ?

**Comment by samarthhapse** [comment]
> one more thing should i add a hamburger for the nav bar for small screen ?

yeah !

**Comment by samarthhapse** [comment]
> @samarthhapse got it . In the mean time i request you to assign this issue a level as well as a gssoc title . thank you.

But be sure that you are adding responsiveness to all pages . sign-in ad sign-up as student and expert and check all pages inside there. You will get 2 to 3 pages after student sign-in and 2-3 pages after expert sign-in

**Comment by samarthhapse** [comment]
@pahuja-sahil I have added labels

**Comment by pahuja-sahil** [comment]
@samarthhapse  i think you should check the sign in option i am not sure there is some problem i can't sign in no matter what i do i have tried everything. i kindly ask you to login on your end to confirm that it is working fine as i have tried everything but it is not working and if i can't login i won't be able to adjust it size for small screens.

**Comment by samarthhapse** [comment]
hello @pahuja-sahil , was quiet busy in last week

**Comment by samarthhapse** [comment]
@pahuja-sahil , there is no problem on my side

**Comment by samarthhapse** [comment]
@pahuja-sahil 

follow these steps to start the app => 

step 1 : fork current branch (temp-af)
step 2 : create .env file in server folder
step 3 : copy paste below code in this .env file (change required credentials , i have shared my personal ones)
step 4 : to start server (backend)
             cd server
             npm install
             node index.js
step 5 : to start client folder (frontend)
             cd client
             npm install
             npm run dev

MONGO_URI="###############################################"
JWT_SECRET_KEY=23142424
MAIL_HOST="smtp.gmail.com"
MAIL_PORT=465
MAIL_AUTH_USER='samarthmanojhapse96.0@gmail.com'
MAIL_AUTH_PASSWORD='##################'
CLOUDINARY_CLOUD_NAME='dn9pyo4zp'
CLOUDINARY_API_KEY='################'
CLOUDINARY_API_SECRET='#####################'

**Comment by VaibhavYT** [comment]
it is assigned to some one else

**Comment by samarthhapse** [comment]
@VaibhavYT comment on issue 214. We will come here after it

**Comment by samarthhapse** [comment]
@pahuja-sahil , no response from 2 weeks. I am unassigning you

**Comment by samarthhapse** [comment]
@VaibhavYT complete with #214 , this issue is awaiting

**Comment by samarthhapse** [comment]
@VaibhavYT , assigned this issue to you , pls do it by today EOD.

**Comment by samarthhapse** [comment]
@VaibhavYT pls raise PR ?

**Comment by samarthhapse** [comment]
@VaibhavYT , where are you lost buddy

**Comment by samarthhapse** [comment]
@VaibhavYT , pls raise PR today only.

**Comment by samarthhapse** [comment]
@VaibhavYT , it has been so long now

**Comment by samarthhapse** [comment]
@VaibhavYT , what's wrong ? please let me now if you are facing any issue.  If you are busy, and do tell if you are not willing to work. I have assigned it to you and you aren't replying.

**Comment by VaibhavYT** [comment]
I was busy.

**Comment by VaibhavYT** [comment]
Assign this issue to someone , if they do that's ok

**Comment by samarthhapse** [comment]
@pani2004 , can you please work on this issue.

**Comment by pani2004** [comment]
@samarthhapse for which page as the home page is responsive

**Comment by samarthhapse** [comment]
For remaining all pages of website. Till you reach payment gateway and chat features.

**Comment by pani2004** [comment]
okk @samarthhapse assign me will give it a try

**Comment by samarthhapse** [comment]
@pani2004 , try to complete by tomorrow EOD

**Comment by samarthhapse** [comment]
@pani2004 assigned to you

**Comment by samarthhapse** [comment]
Hello @pani2004 , Actually I did not get time to review your previous PR. But you added 500 Rs payment amount there. Pls keep it editable for student. Please make it like student will enter the amount and then pay it.
