### ISSUE TITLE
Enhancement of student and expert choosing page

### ISSUE THREAD

**Issue by samarthhapse** [samarthhapse/sarthi#214]
from landing page , when you click ik login. You will get a page with 2 options (student & expert). You have to change that ui , add something interesting and 3D seeming ui there

**Comment by VaibhavYT** [comment]
okay I will make his page more good

**Comment by VaibhavYT** [comment]
assign me and add gssoc level

**Comment by samarthhapse** [comment]
@VaibhavYT assigned

**Comment by VaibhavYT** [comment]
Thanks

**Comment by samarthhapse** [comment]
@VaibhavYT , hope it is done

**Comment by samarthhapse** [comment]
Pls raise pr asap

**Comment by VaibhavYT** [comment]
give me some time , I am busy in my office works,
I will raise pr when I will complete , I have already started working....

**Comment by samarthhapse** [comment]
okay no problem , just try to be quick

**Comment by samarthhapse** [comment]
Hello @VaibhavYT , pls hurry man

**Comment by samarthhapse** [comment]
Hello @VaibhavYT pls hurry

**Comment by samarthhapse** [comment]
@VaibhavYT it has beem 3 days you are working on same issue

**Comment by samarthhapse** [comment]
@VaibhavYT when the PR will be raised

**Comment by VaibhavYT** [comment]
today it will be completed

**Comment by samarthhapse** [comment]
okay @VaibhavYT

**Comment by samarthhapse** [comment]
Hello @VaibhavYT

**Comment by samarthhapse** [comment]
@VaibhavYT , it's delayed so much

**Comment by samarthhapse** [comment]
@VaibhavYT when you will raise pr

**Comment by VaibhavYT** [comment]
I don't know what to say , but I will try to complete it by today

**Comment by samarthhapse** [comment]
@VaibhavYT pls do it by today EOD only

**Comment by VaibhavYT** [comment]
May I change the bg of page?

**Comment by VaibhavYT** [comment]
I had raised the PR, please have a look

**Comment by samarthhapse** [comment]
@VaibhavYT available for #240 ?

**Comment by VaibhavYT** [comment]
From Wednesday
