### ISSUE TITLE
Integration of online meeting feature (MERN stack)

### ISSUE THREAD

**Issue by samarthhapse** [samarthhapse/sarthi#215]

**Comment by AbhiDiva96** [comment]
Hey @samarthhapse 
Pls assign it to me

**Comment by AbhiDiva96** [comment]
I will develop it using webrtc.
@samarthhapse

**Comment by samarthhapse** [comment]
well @AbhiDiva96. You can start working immediately. Try to raise PR asap

**Comment by AbhiDiva96** [comment]
Got it @samarthhapse

**Comment by samarthhapse** [comment]
@AbhiDiva96
Description :
When student signin , and chooses the expert of his choice. He will be landed on this page. You are expected to create a button on this page, which will have the feature to conduct the meet between student and the expert

reference => https://github.com/0x5eba/Video-Meeting

![Screenshot 2024-07-19 224028](https://github.com/user-attachments/assets/18796e1a-8338-4a47-8b9c-f70a0ec45097)
6

**Comment by samarthhapse** [comment]
@AbhiDiva96 feel free to ask any small doubt , but do not make any misunderstanding

**Comment by AbhiDiva96** [comment]
Is there any transaction process that will be conducted before connecting to export??

**Comment by samarthhapse** [comment]
@AbhiDiva96 , I will be integrating authorization process later , currently just build simply like provided reference and added the icon on above page

**Comment by samarthhapse** [comment]
@AbhiDiva96 , pls comment with the date when the PR will be raised

**Comment by samarthhapse** [comment]
@AbhiDiva96 , hope it is completed, Pls raise PR by today EOD

**Comment by AbhiDiva96** [comment]
It will take two more days pls give me time @samarthhapse

**Comment by samarthhapse** [comment]
ok, take 2 days. but complete it fully, it must work without any fail

**Comment by samarthhapse** [comment]
@AbhiDiva96  it has been more than 4 days brother. When are you raising PR. Do it today only

**Comment by AbhiDiva96** [comment]
It's taking time due to some functionality if u don't mind can I raise pr till 29. I will be thankful to you. @samarthhapse

**Comment by samarthhapse** [comment]
@AbhiDiva96 take 2 more days. But I request you that , just do not go on backfoot at last moment. If you have any small doubt , ask me.

**Comment by samarthhapse** [comment]
> It's taking time due to some functionality if u don't mind can I raise pr till 29. I will be thankful to you. @samarthhapse

Go ahead !

**Comment by samarthhapse** [comment]
@AbhiDiva96 , how is it going ?

**Comment by samarthhapse** [comment]
hello @AbhiDiva96 , I was bit busy from last 2-3 days. I haven't reviewed the code before. But now as I am trying to create meeting , I am not getting any response. I am just getting the below page. Why is it so ?

<img width="960" alt="Annotation 2024-08-01 191559" src="https://github.com/user-attachments/assets/55cf2027-d339-4308-a468-97f7a5eca311">

**Comment by samarthhapse** [comment]
@AbhiDiva96 , pls reply

**Comment by AbhiDiva96** [comment]
Run websocket backend code @samarthhapse

**Comment by samarthhapse** [comment]
haven't you added it's reference in main file (index.js)

**Comment by samarthhapse** [comment]
@AbhiDiva96 , can you pls add it in main file so it can become active on running actual backend with (index.js)

**Comment by AbhiDiva96** [comment]
I had added it into the separate file. 
I added it because it needs a separate file at that point of time, if you want I will merge it to the main index.js file
@samarthhapse

**Comment by samarthhapse** [comment]
@AbhiDiva96 Pls make it like following : 

1. firstly I will start server via command (node index.js) & client by  (npm run dev)

2. then further when I will click on create meeting it should work at that time.

3. I think , I have asked to add the button on the below page (when student select one expert he gets the below page) but you added it on Landing page (please change it)

![Screenshot 2024-07-19 224028](https://github.com/user-attachments/assets/adb1239d-61ff-4a08-9e57-1b7eff5466b2)

**Comment by samarthhapse** [comment]
@AbhiDiva96 , I opened a new level3 issue #234  for above 3 changes. Pls try to raise PR asap, mostly by today evening.
I will assign it to you

**Comment by AbhiDiva96** [comment]
I haven't seen this page can u provide me the path of the page @samarthhapse

**Comment by samarthhapse** [comment]
you get this page when you sign in as student and choose one expert of your choice

**Comment by AbhiDiva96** [comment]
Ooh I haven't connected the backend due to some issues. By any chance I can get that page directly. @samarthhapse

**Comment by AbhiDiva96** [comment]
> @AbhiDiva96 , I opened a new level3 issue #234  for above 3 changes. Pls try to raise PR asap, mostly by today evening.
> I will assign it to you

Why I didn't get any leave on the previous merged PR #215 , there was any issue.

**Comment by samarthhapse** [comment]
added labels for #226

**Comment by samarthhapse** [comment]
pls run main backend, for simplicity I am providing you with my own .env file

**Comment by samarthhapse** [comment]
@AbhiDiva96 wait for 2 hours. I will guide you to run backend and frontend properly

**Comment by AbhiDiva96** [comment]
Got it @samarthhapse
