### ISSUE TITLE
Integration of payment gateway 

### ISSUE THREAD

**Issue by samarthhapse** [samarthhapse/sarthi#216]

**Comment by pani2004** [comment]
@samarthhapse Will try to work on it but need some time because my classes have started

**Comment by pani2004** [comment]
U can assign me

**Comment by samarthhapse** [comment]
@pani2004 pls do share your personal mail, I will provide you with secret keys of Razorpay

**Comment by pani2004** [comment]
debashispani61@gmail.com @samarthhapse

**Comment by samarthhapse** [comment]
@pani2004 mailed you

**Comment by pani2004** [comment]
Recived  @samarthhapse

**Comment by pani2004** [comment]
@samarthhapse for which feature will I add the payment option?

**Comment by pani2004** [comment]
@samarthhapse Pls give the details

**Comment by samarthhapse** [comment]
sorry for delay from my side. Hope you have completed till the endpoint

**Comment by samarthhapse** [comment]
@pani2004 , you just have to add icon to pay on the below page.

![Screenshot 2024-07-19 224028](https://github.com/user-attachments/assets/a64d78e1-fc15-4f78-96cc-fd062da6d5f5)

**Comment by pani2004** [comment]
@samarthhapse which route is this?

**Comment by samarthhapse** [comment]
are you getting chatting option. Are you able to chat

**Comment by pani2004** [comment]
no chat option

**Comment by pani2004** [comment]
@samarthhapse i had not created an expert that's why it was not showing to me , will now add the pay now button in that page and will raise the pr in the next 2days.
