### ISSUE TITLE
[Feature Request]: To Add Multilingual feature of Google Translate.

### ISSUE THREAD

**Issue by Anushkajoshii** [samarthhapse/sarthi#219]
Users can navigate and interact with the website in their chosen language, enhancing accessibility and user experience.

Benefits:-

Provides users from diverse linguistic backgrounds with the ability to read and understand website content in their preferred language, improving overall accessibility.
By catering to a global audience, the website can attract and retain users who prefer or need content in languages other than the default.
Reduces language barriers, allowing users to interact more effectively with the site, which can lead to higher satisfaction and longer visit durations.
I would like to work on this, kindly assign me this under GSSOC'24 .

<img width="1285" alt="Screenshot 2024-07-19 at 9 38 27 PM" src="https://github.com/user-attachments/assets/a1893c05-ead0-41d4-bc2e-0c8acaff1cb4">

Users can navigate and interact with the website in their chosen language, enhancing accessibility and user experience.

Benefits:-

Provides users from diverse linguistic backgrounds with the ability to read and understand website content in their preferred language, improving overall accessibility.
By catering to a global audience, the website can attract and retain users who prefer or need content in languages other than the default.
Reduces language barriers, allowing users to interact more effectively with the site, which can lead to higher satisfaction and longer visit durations.
I would like to work on this, kindly assign me this under GSSOC'24 .
Screenshot 2024-07-19 at 9 04 50 PM
This will be the outcome.

**Comment by samarthhapse** [comment]
@Anushkajoshii , good thought ! Assigning this issue to you. Raise PR asap (probably within 2-3 days)

**Comment by Anushkajoshii** [comment]
hey, @samarthhapse i've raise PR, do check it out, and i request you to assign the required level and gssoc tags. 
Thankyou

**Comment by samarthhapse** [comment]
@Anushkajoshii , will merge by tomorrow. Pls wait

**Comment by Anushkajoshii** [comment]
@samarthhapse Thanks for the update!
