### ISSUE TITLE
expert verification from side of website owner

### ISSUE THREAD

**Issue by samarthhapse** [samarthhapse/sarthi#224]
Whenever any expert try to sign up here , owner of website (example@gmail.com) should get a mail to review that expert. When owner verify the expert then only the expert profile should get created

**Comment by aarushi-shanker** [comment]
I can work on it, please assign me. I will get it done at the earliest

**Comment by samarthhapse** [comment]
fine @aarushi-shanker , start working. Try to complete it within 2 days.

**Comment by samarthhapse** [comment]
@aarushi-shanker assigned it to you. Please make hurry to  raise PR.

**Comment by samarthhapse** [comment]
@aarushi-shanker , you are working on it right ?

**Comment by aarushi-shanker** [comment]
Yes I am working on it.

**Comment by samarthhapse** [comment]
well , keep going !

**Comment by aarushi-shanker** [comment]
Hey I am getting issues cloning the repo. maybe it's the size of the project. 
The error - fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output.
Tried solving this issue for some time, couldn't resolve it.
I am sorry, I don't think I can work on it.

**Comment by samarthhapse** [comment]
wait , I will share solution by evening

**Comment by samarthhapse** [comment]
Hello @aarushi-shanker , I was quite busy in last 2-3 days

**Comment by samarthhapse** [comment]
@aarushi-shanker , why are you getting this error. Try to simply download zip file of the code. It is working for other contributors

**Comment by samarthhapse** [comment]
@aarushi-shanker , if you can pls do it now. I am available to solve basic issue today
