### ISSUE TITLE
pay2

### ISSUE THREAD

**Issue by samarthhapse** [samarthhapse/sarthi#230]

**Comment by pani2004** [comment]
@samarthhapse assign me

**Comment by samarthhapse** [comment]
@pani2004 assigned

**Comment by samarthhapse** [comment]
@pani2004 , can you pls try to raise PR by tonight only

**Comment by pani2004** [comment]
okk @samarthhapse

**Comment by samarthhapse** [comment]
hello @pani2004 , can you pls work for responsiveness of some remaining pages

**Comment by samarthhapse** [comment]
@pani2004 ,if you can pls comment on #240 , I will assign it to you

**Comment by samarthhapse** [comment]
@pani2004 , now I have merged the prs. Now the code is working fine. Pls add responsiveness for remaining all pages

**Comment by pani2004** [comment]
okk @samarthhapse will do it
