### ISSUE TITLE
expert profile verification

### ISSUE THREAD

**Issue by AADESHak007** [samarthhapse/sarthi#231]
**Describe the bug**
For checking if the user already exists or not you are making 2 DB calls that is really expensive in the context of development.

**Proposed Solution**
I can optimize the code for you and will check for some optimizations too.

**Screenshots**
![Screenshot 2024-08-01 202438](https://github.com/user-attachments/assets/bcda3aae-957a-40fd-a084-7a402880ef0e)

**Desktop (please complete the following information):**
 - OS: [windows 10]
 - Browser [chrome, ]
 - Version [ 22]

**Comment by AADESHak007** [comment]
It would be really appreciable if you could assign this task to me I will be able to solve it by today .

**Comment by samarthhapse** [comment]
@AADESHak007 , this issue is not that urgent. but if you can work on below problem issue so pls comment below and start building. I will assign you => 

Issue => 
Whenever any expert try to sign up here , owner of website ([example@gmail.com](mailto:example@gmail.com)) should get a mail to review that expert. When owner verify the expert then only the expert profile should get created

**Comment by AADESHak007** [comment]
Hey @samarthhapse thank you  for the reply . I would like to check it out . So please assign the task to me .
 I will do something about it and I think I will be able to solve it . If not then I will tell you by tomorrow .

**Comment by samarthhapse** [comment]
great ! pls start working. Assigned the task to you

**Comment by samarthhapse** [comment]
please complete it on urgent basis

**Comment by AADESHak007** [comment]
thanks . I will do it within 2 days .

**Comment by samarthhapse** [comment]
okay, go ahead !

**Comment by samarthhapse** [comment]
hello , @AADESHak007 , to make your task simple. I have added complete code for email verification. Please clone the current branch (updates) and check it out

**Comment by samarthhapse** [comment]
@AADESHak007 hope you haven't started yet

**Comment by samarthhapse** [comment]
@AADESHak007 a PR for this issue is raised by one previous contributor. Pls don't mind , but I have to merge it.

**Comment by samarthhapse** [comment]
@AADESHak007 , if you are well experienced in mern backend so I can assign you another issue. Are you ready ?

**Comment by AADESHak007** [comment]
Actually I had built a working code for the whole feature  and was testing it on my local app and system, but no worries I ll check it and tell you if there are any upgrades that we can do

**Comment by AADESHak007** [comment]
I want to contribute on the project so please feel free assign me a task .

**Comment by samarthhapse** [comment]
@AADESHak007 , currently when I try to authorize expert , I have to do it from localhost only. Do you have any solution for it. So I can authorize from that mail id without localhost

**Comment by samarthhapse** [comment]
If you have completed , pls share the complete working video of your solution

**Comment by samarthhapse** [comment]
@AADESHak007 if I find your task better than current one I will merge your PR

**Comment by samarthhapse** [comment]
@AADESHak007 pls share the video

**Comment by AADESHak007** [comment]
I have checked the code and it looks good to me . 
However I was also working on the last part .
If the administrator confirms the registration then the user should get a code that could get verified first then only the expert is allowed to register.

**Comment by samarthhapse** [comment]
Currently it is on click of link so it is needing localhost.  If we add integrate code verification,  we will not need localhost. It will go smooth like otp verification.

**Comment by samarthhapse** [comment]
@AADESHak007 pls try to make it and raise PR

**Comment by samarthhapse** [comment]
@AADESHak007 pls try to make it and raise PR. Is it possible by tonight

**Comment by AADESHak007** [comment]
I ll try to do it by tonight .. I ll do it when I reach home at 7

**Comment by AADESHak007** [comment]
DONE✅

Hey @samarthhapse i have completed the whole thing and it is working fine . 
**SCREENSHOTS**
![owners_end](https://github.com/user-attachments/assets/ca2a0463-b2c2-4893-90a4-b2f1703b4b7a)
![Screenshot 2024-08-02 215754](https://github.com/user-attachments/assets/d195a12d-3802-400f-8c43-af42cf85d714)
![Screenshot 2024-08-02 215818](https://github.com/user-attachments/assets/8426aeb5-a7b2-4a24-baa3-c157b1a151d5)

before creating a PR I have change the whole auth-expert.js . If you are fine with that then only I will do that .
PLEASE RESPOND ASAP..

**Comment by samarthhapse** [comment]
@AADESHak007 , but you must be careful that rest of the functionalities based on auth-expert.js should work properly

**Comment by samarthhapse** [comment]
@AADESHak007  also while sending mail pls try to share the details with it like below image

![auth](https://github.com/user-attachments/assets/b19c9029-a879-47f5-9b67-e176bd93378b)

**Comment by AADESHak007** [comment]
@samarthhapse please check the new branch /feat/authorization-updated
