### ISSUE TITLE
meet improvement

### ISSUE THREAD

**Issue by samarthhapse** [samarthhapse/sarthi#234]

**Comment by samarthhapse** [comment]
@AbhiDiva96 available now. Can we connect on discord

**Comment by samarthhapse** [comment]
@AbhiDiva96  Let us discuss there . I will help you to run the app

**Comment by AbhiDiva96** [comment]
Sure @samarthhapse

**Comment by samarthhapse** [comment]
sama1595

**Comment by samarthhapse** [comment]
I shared my username and assigned this issue to you. Let us connect there

**Comment by AbhiDiva96** [comment]
abhidiva 
I sent you request @samarthhapse

**Comment by samarthhapse** [comment]
@AbhiDiva96 , I reviewed the code but it is just showing camera when I click on create meeting. How expert and student will connect there

**Comment by AbhiDiva96** [comment]
I was just created to end point first one is creating meeting and second one is join meeting using that Id but in current page need to connect that I'd with expert page automatically. @samarthhapse 
That's why it showing that page only.

**Comment by samarthhapse** [comment]
@AbhiDiva96 I have provided you the one reference, please go through reference again =>
https://github.com/0x5eba/Video-Meeting?tab=readme-ov-file

such feature was expected

**Comment by samarthhapse** [comment]
@AbhiDiva96 , I am merging your PR , and assigning the further task to someone else.

**Comment by samarthhapse** [comment]
@AbhiDiva96 , Have some issues regarding frontend , are you available to resolve

**Comment by samarthhapse** [comment]
@AbhiDiva96 , merged your PR, but had conflicts in another PR. Can you pls raise the previous PR on temp-of branch.

**Comment by samarthhapse** [comment]
@AbhiDiva96 , also comment if you are ready for some frontend part

**Comment by AbhiDiva96** [comment]
> @AbhiDiva96 , merged your PR, but had conflicts in another PR. Can you pls raise the previous PR on temp-of branch.

Ok I will raise it @samarthhapse

**Comment by AbhiDiva96** [comment]
> @AbhiDiva96 , also comment if you are ready for some frontend issues

Actually I am little busy,  you can assign someone else. @samarthhapse

**Comment by samarthhapse** [comment]
okay @AbhiDiva96
