### ISSUE TITLE
video-meet&chat

### ISSUE THREAD

**Issue by samarthhapse** [samarthhapse/sarthi#238]
I am providing the reference below. It is the proper repo for the feature we need. The task is to just integrate the feature on click of connect button (when student/expert clicks on connect button he must get the feature similar to the provided reference)

reference => https://github.com/DanValMont/merged-video-call-chat-web-app

**Comment by ishuvam009** [comment]
@samarthhapse checking

**Comment by ishuvam009** [comment]
@samarthhapse give me some time, i need to understand this WEBRTC thing.

**Comment by samarthhapse** [comment]
you will get the code on reference repo, you jus need to add that complete web app onclick of connect button

**Comment by ishuvam009** [comment]
@samarthhapse should (onClick) should redirect to that page or should a make a coplete another app using the codebase?

**Comment by samarthhapse** [comment]
@ishuvam009 no , not another app. Just integrate the whole app in one button of this project
