### ISSUE TITLE
backend initialization + student and expert backend

### ISSUE THREAD

**Issue by ayann07** [samarthhapse/sarthi#24]
I will initialize the backend using MVC structure, moreover I will write the backend for student and expert.
I will implement the controllers for register, login, change password , get details of all experts/students and get details of a single expert/ student .
I am working on this under GSSOC'24.

**Comment by ArchitGoyal2005** [comment]
Kindly assign me this issue under GSSOC'24.

**Comment by ayann07** [comment]
@samarthhapse please see to it and I have completed this work aswell.
