### ISSUE TITLE
react-frontend & responsiveness

### ISSUE THREAD

**Issue by samarthhapse** [samarthhapse/sarthi#240]

**Comment by pani2004** [comment]
@samarthhapse can u specify the pages because other pages are still not there. Getting a 404 not found page

**Comment by samarthhapse** [comment]
@pani2004 I need to merge one PR . Can you pls wait for today ? I will inform you when the working code is updated.

**Comment by pani2004** [comment]
@samarthhapse assign

**Comment by samarthhapse** [comment]
@pani2004 assigned .

do check for all the remaining pages and add responsiveness (only for laptop and mobile)

**Comment by samarthhapse** [comment]
Hello @pani2004, done ?

**Comment by pani2004** [comment]
@samarthhapse yes yess will do it

**Comment by pani2004** [comment]
@samarthhapse only made the expert profile page responsive, but no other new pages are added

**Comment by samarthhapse** [comment]
Signin , signup , forgot password, exoerts display page , chat section , video meet , payment gateway , .....are they all responsive currently ?

**Comment by pani2004** [comment]
only forgot password is not responsive, will work on that otherwise all others are fine

**Comment by samarthhapse** [comment]
@pani2004  okay, go ahead pls

**Comment by samarthhapse** [comment]
@pani2004  also try to do several small changes that will seem to be working fine on mobile and laptop. Like hamburger menu is not closing on clicking login(for mobile),etc.....small changes that will make user experience smoother and good

**Comment by samarthhapse** [comment]
pls try to raise PR by tomorrow afternoon only

**Comment by pani2004** [comment]
I am in college right now will do it tonight!!

**Comment by samarthhapse** [comment]
@pani2004 in the navbar add a moon & sun icon instead of light and dark mode button. Pls raise PR by 11:59 PM only

**Comment by samarthhapse** [comment]
@pani2004 , also remove this scrollbar. You can add webkit for it.

<img width="260" alt="Annotation 2024-08-08 154117" src="https://github.com/user-attachments/assets/24f8923b-30a9-45a3-8577-f61bca9a99ef">

**Comment by samarthhapse** [comment]
@pani2004 , I am listing all changes below.

1. responsiveness for forgot password pages (expert and student both)
2. for mobile hamburger menu should close onclick of any <li>
3. moon/sun icon in navbar instead of the dark/light button
4. remove scrollbar
5. change position of translator icon (on laptop as well as mobile screens)

**Comment by samarthhapse** [comment]
![InkedAnnotation 2024-08-08 154117_LI](https://github.com/user-attachments/assets/6fc34053-c021-465f-89fb-21ebc372e01b)

**Comment by samarthhapse** [comment]
> @pani2004 , I am listing all changes below.
> 
> 1. responsiveness for forgot password pages (expert and student both)
> 2. for mobile hamburger menu should close onclick of any
> 4. moon/sun icon in navbar instead of the dark/light button
> 5. remove scrollbar
> 6. change position of translator icon (on laptop as well as mobile screens)

@pani2004 pls raise pr by 11:59 only. It is needed today

**Comment by pani2004** [comment]
okk

**Comment by samarthhapse** [comment]
Hello @pani2004, it might be about to complete , one additional change in name "Sarthi" on navbar=>
1. reduce it's font size to bit smaller
2. change font style to cursive and make it's color dark orange
