### ISSUE TITLE
meet frontend

### ISSUE THREAD

**Issue by samarthhapse** [samarthhapse/sarthi#245]

**Comment by samarthhapse** [comment]
hello @ishuvam009 , comment below I will assign it to you

**Comment by ishuvam009** [comment]
@samarthhapse i will complete it by tomorrow.

**Comment by ishuvam009** [comment]
I mean today ie 05/08/24.

**Comment by samarthhapse** [comment]
okay @ishuvam009 , no problem. Go ahead !

**Comment by samarthhapse** [comment]
@ishuvam009 assigned to you

**Comment by samarthhapse** [comment]
@ishuvam009 hope it is completed. Pls raise the PR

**Comment by ishuvam009** [comment]
@samarthhapse please check your Discord
