### ISSUE TITLE
frontend changes

### ISSUE THREAD

**Issue by samarthhapse** [samarthhapse/sarthi#247]
1. remove sign-up with google feature (with it's complete code from frontend and backend) #179 
2. Remove this let's meet button and code related to that feature. #226 
3. try to add that language translator in any small icon, it is taking so much space on main home page

**Comment by samarthhapse** [comment]
@ishuvam009 , do ask on discord if you have any doubt

**Comment by samarthhapse** [comment]
<img width="960" alt="Annotation 2024-08-06 150444" src="https://github.com/user-attachments/assets/7b6cad6b-fcab-475e-83fb-c177bd04aab4">

for problem no.2 of description => remove that Let's meet button from left corner along with complete code related to that feature

**Comment by samarthhapse** [comment]
<img width="580" alt="Annotation 2024-08-06 180920" src="https://github.com/user-attachments/assets/7d26b2c5-7655-48c2-8789-055d60541c75">

for problem no.3 of description => remove that 'Signup with google"  button from right corner along with complete code related to that feature

**Comment by samarthhapse** [comment]
@ishuvam009 solved all 3 of them ?

**Comment by anwesha2002** [comment]
@samarthhapse I am agssoc'24 contributor can u assign this to me??

**Comment by samarthhapse** [comment]
@ishuvam009 , pls comment here as completed so I will assign and close it. So you will get points for this issue

**Comment by ishuvam009** [comment]
@samarthhapse Complete ✅️
