### ISSUE TITLE
Update README for Improved Documentation

### ISSUE THREAD

**Issue by jinx-vi-0** [samarthhapse/sarthi#30]
Clear and well-structured documentation is crucial for users and contributors to understand the project, its purpose, and how to get started

hey @samarthhapse , please assign this issue to me.

**Comment by Suruchibharti** [comment]
hey,
I'm GSSoC'24 contributor , I have experienced on HTML, CSS, JS, and react.js , so I want to work on this issue,
so, kindly requested to you to assign me the task.

**Comment by samarthhapse** [comment]
@jinx-vi-0 you can work this ,an make a pr after you re completed

**Comment by jinx-vi-0** [comment]
hey @Suruchibharti , this issue is already assigned to me.

**Comment by jinx-vi-0** [comment]
hey @samarthhapse , I've submitted a pull request. Could you please add labels to the issue to better track it.

**Comment by iamkanhaiyakumar** [comment]
I've noticed your project lacks a README.md file, crucial for sharing essential project details and fostering collaboration. As a GSSoC 2024 participant, I'm keen on contributing meaningfully. Can you assign me this task? I'm dedicated to crafting a thorough README for the project's benefit. Thanks for considering. Eagerly awaiting your response.

Thank u @samarthhapse

**Comment by jinx-vi-0** [comment]
@iamkanhaiyakumar , I had already submitted a pr.
