### ISSUE TITLE
Tech career assistance page

### ISSUE THREAD

**Issue by Hrishita-Paul** [samarthhapse/sarthi#33]
@samarthhapse I would like to design the frontend of the tech career assistance page. I have worked previously in this area so I would like to contribute under GSSoC 2024.

**Comment by Hrishita-Paul** [comment]
Please assign this issue to me. I am eager to contribute in GSSoC.

**Comment by Daksh-khandelwal-1495** [comment]
Hi there ! @samarthhapse 

Would love to get started on this project for creating a tech career assistance page. 
I have had some good experience in designing web pages, which would be helpful for the same. 

Looking forward to it.

**Comment by Yuvraj960** [comment]
@samarthhapse Please assign this issue to me under GSSoC24

**Comment by K-21** [comment]
@Hrishita-Paul Can you please assign me this issue under GSSOC''24

**Comment by shrerai** [comment]
Please assign this issue to me under GSSoC24.

**Comment by shrerai** [comment]
@samarthhapse  Please assign this issue to me under GSSoC24.

**Comment by akilesh1706** [comment]
@Hrishita-Paul Can you assign it to me as part of gssoc'24

**Comment by samarthhapse** [comment]
@Hrishita-Paul , @Daksh-khandelwal-1495 , @akilesh1706 , @shrerai , Hello everyone there #90  if you are experienced in advanced react and tailwind and willing to work on creating a cool profile page
