### ISSUE TITLE
[Enhancement] Docker and Docker-Compose files 

### ISSUE THREAD

**Issue by MishraTanishq619** [samarthhapse/sarthi#34]
This issue proposes the addition of Dockerfiles and Docker Compose configuration to streamline the deployment and development process of the project.

- [ ] Create Dockerfiles 
- [ ] Implement Docker Compose 
- [ ] Update ReadMe accordingly

**Comment by MishraTanishq619** [comment]
I would Like to work on this myself.
Please assign me this, for GSSOC.

**Comment by samarthhapse** [comment]
I will open this issue in the ending part of project again.

**Comment by MishraTanishq619** [comment]
ok..
