### ISSUE TITLE
FEAT: raising a complain if any misbehavior is caused.

### ISSUE THREAD

**Issue by aditikhare16** [samarthhapse/sarthi#36]
**Describe the bug**
There should be a "report" option in case any junior/senior causes scam, misbehavior, etc. The issue should be reviewed and necessary actions should be taken.

**To Reproduce**
1. Go to 'three dots on the chatbox'
2. Click on 'Report'
3. Type the complain
4. Submit

**Expected behavior**
Necessary actions should be taken after reviewing the complain. 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
This will create a safe, clean and better community for the users.

**Comment by samarthhapse** [comment]
@aditikhare16 start working on it . After completion keep it with you only . I will add th chat functionality code further then make a fork and add your report feature there

**Comment by aditikhare16** [comment]
Sure, thank you for the opportunity!
