### ISSUE TITLE
FEATURE: Rating the helper.

### ISSUE THREAD

**Issue by aditikhare16** [samarthhapse/sarthi#37]
**Describe the bug**
Rating and reviewing the senior/expert who helped.

**To Reproduce**
1. Go to 'Profile of the expert'
2. Click on 'Feedback'
3. Scroll down to 'Star /5'
4. Write feedback
5. Submit.

**Expected behavior**
This will help in justifying the payment charged by the expert and enable others to request help accordingly.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
The reviews and feedbacks of experienced users can be really helpful for the new users while approaching for help.

**Comment by aditikhare16** [comment]
Please assign me this issue under gssoc24

**Comment by samarthhapse** [comment]
you can complete separately further after prev. add-ons, you will also have to connect with main app

**Comment by samarthhapse** [comment]
@aditikhare16 are you working on it ?

**Comment by aditikhare16** [comment]
Yes, I'm working on it! My semester exams are clashing, so I'm really sorry for the delay, but I'm working on this!

**Comment by Ketanop321** [comment]
please provide a live link of your code

**Comment by Yuvraj960** [comment]
@samarthhapse Please assign this issue to me under GSSoC24

**Comment by aditikhare16** [comment]
Sir I humbly request you to please assign this to me as I suggested this feature, and I am working on it as well.

**Comment by K-21** [comment]
@aditikhare16 can you please assign this to me GSSOC'24

**Comment by samarthhapse** [comment]
@aditikhare16 can you make it in 2 days

**Comment by samarthhapse** [comment]
Hello @K-21 , are you experienced in MERN
