### ISSUE TITLE
FEATURE : Filtering experts based on their expertise.

### ISSUE THREAD

**Issue by aditikhare16** [samarthhapse/sarthi#38]
**Describe the bug**
The experts/seniors should enter their expertise. The new users can seamlessly filter according to their requirements and approach the appropriate expert for help. 

**To Reproduce**

**Expected behavior**
The skills of experts should be added as tags while creating their account. The experts can easily then be filtered according to their expertise.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
This will help students search an expert with a particular skill very easily.

**Comment by aditikhare16** [comment]
Please assign me this issue under gssoc'24.

**Comment by nishant0708** [comment]
can you assign me this issue.under gssoc24

**Comment by aditikhare16** [comment]
Please assign me this issue as I opened it and I am working on it as well, under GSSOC'24.

**Comment by samarthhapse** [comment]
@aditikhare16 will it be possible for you to complete this issue within two days ? I am adding the code tonight. I will comment here after merging that PR. Then you can fork and start working on this issue.

**Comment by samarthhapse** [comment]
comment if you can complete it by 5 June EOD

**Comment by samarthhapse** [comment]
No problem @aditikhare16 , now multiple PR's are merged in the way between, tomorrow I will merge one more PR. Then you can fork temp branch and work on it. Tomorrow I will provide you the complete description for this issue.

**Comment by samarthhapse** [comment]
Comment what is the date by you can complete it ?

**Comment by aditikhare16** [comment]
Thank you so much for your help and support!! I will not let you down!

**Comment by samarthhapse** [comment]
TASK : after student login he must get three sections to choose 
1.Bug solving
2.Tech career assistance
3.Academic support
after selecting the section from above mentioned options , student must get list of all experts available in DB for the specific option

**Comment by samarthhapse** [comment]
@aditikhare16 can you complete this task by 10 EOD

**Comment by aditikhare16** [comment]
> @aditikhare16 can you complete above task by 10 EOD

By 12th EOD, It'll be definitely completed! 
I'm sorry for the delay and thank you for your help!

**Comment by samarthhapse** [comment]
no worries , just do it by 12 EOD. Do you want any details ?

**Comment by samarthhapse** [comment]
TASK : after student login he must get three sections to choose
1.Bug solving
2.Tech career assistance
3.Academic support
after selecting the section from above mentioned options , student must get list of all experts available in DB for the specific option

**Comment by samarthhapse** [comment]
@aditikhare16 please start now and raise PR by 12 EOD only.

**Comment by aditikhare16** [comment]
Ok, I will do it.

**Comment by samarthhapse** [comment]
@aditikhare16 how's it going , any doubt ?

**Comment by samarthhapse** [comment]
@aditikhare16 any update ?

**Comment by samarthhapse** [comment]
@aditikhare16 completed ?

**Comment by samarthhapse** [comment]
@aditikhare16 pls reply

**Comment by samarthhapse** [comment]
@aditikhare16 deadline is over

**Comment by aditikhare16** [comment]
You may unassign me and assign to someone who will be able to do this
efficiently.
I have built this, but it's throwing a lot of errors and not working
properly.
I am really sorry for the inconvenience caused and thank you for giving
me this opportunity and time.

**Comment by samarthhapse** [comment]
No worries @aditikhare16 ,don't say sorry. But the thing is , If you are not getting it just inform asap. Btw , it's okay
