### ISSUE TITLE
[Feature] : Implement the Home Ui

### ISSUE THREAD

**Issue by sivaprasath2004** [samarthhapse/sarthi#39]
**Describe the bug**
- If i want implement for best of the ui for this project i will suggest.
- i will ready for work.

### Model Of the Ui
[Screencast from 2024-05-13 18-32-30.webm](https://github.com/samarthhapse/sarthi/assets/121082414/9d0b6e39-9a74-4e0b-86a4-7ce0548ec353)
- To change clock to the Count `button` update the `state` hook and proper design to adopt to customize.

**Comment by sivaprasath2004** [comment]
@samarthhapse i will waiting for the assign.... :computer:

**Comment by anshdeep0504** [comment]
Hey, allow me to work on this under GSSOC' 2024
