### ISSUE TITLE
💡[Feature]: Creating the landing page Interactive and User-Friendly

### ISSUE THREAD

**Issue by Priyanshu2743** [samarthhapse/sarthi#45]
Hii @samarthhapse 

I will create a main front page for the SARTHI with a great UI and great User-Interaction 
which will include the 
-- Logo
-- Content 
-- Nav Bar
-- Different Sections (Testimonials, Reviews, FAQ)
-- Footer

All with a great user Interaction 
with AOS, Vanilla JS and a lot of more impressive effects

Kindly Assign me this under GSSOC2024 and add labels

**Comment by samarthhapse** [comment]
Welcome @Priyanshu2743 , This issue is already opened earlier ,please comment on #14. I am closing this issue.
