### ISSUE TITLE
Updating user field

### ISSUE THREAD

**Issue by ayann07** [samarthhapse/sarthi#47]
After junior/student's login, they must get 3 fields to choose:

Bug solving

Tech career assistance

Academic support

Backend:

Update the user profile to include the selected assistance fields

Handle user preferences and choices in the backend. I will implement this functionality, please assign me this. I am going to do this under gssoc 24

**Comment by cpratik1307** [comment]
I am thrilled to be participating in GirlScript Summer of Code 2k24 as a passionate computer science student with a keen interest in web development. I am eager to contribute to your project and leverage my skills to make meaningful contributions. I look forward to collaborating with you and the team to create impactful solutions.
@samarthhapse Sir, I would really like to work on this issue under Gssoc'24, so please assign it to me.

**Comment by samarthhapse** [comment]
After choosing these field they user should also get the list of registered experts in the that field.

**Comment by samarthhapse** [comment]
@ayann07 and @cpratik1307 , Who is able to integrate both the features ?

**Comment by ayann07** [comment]
@samarthhapse I will be able to integrate both features.

**Comment by cpratik1307** [comment]
> @ayann07 and @cpratik1307 , Who is able to integrate both the features ?

@samarthhapse, please allow me to work on both features.

**Comment by cpratik1307** [comment]
> @cpratik1307 better if you create your own new issues , I have created this issue so please let me work on this. Thankyou.

Ok no problem @ayann07 Sir,You can work on this problem, sir. However, please let me know if you are working on any other problems.

**Comment by ayann07** [comment]
Assign me this under gssoc'24

**Comment by divyanshu255** [comment]
Assign me this under gssoc'24

**Comment by samarthhapse** [comment]
@divyanshu255 this issue is already assigned anywhere else. Please comment on #116 , I have another issue for you.
