### ISSUE TITLE
 adding login/signup with google functionality

### ISSUE THREAD

**Issue by Isha1233** [samarthhapse/sarthi#60]

**Comment by Isha1233** [comment]
@samarthhapse kindly assign this issue to me I had word previously on this functionality

**Comment by KhushiPrasad** [comment]
Hey @samarthhapse I am a GSSOC contributor, I would like to work on this issue, please assign this issue to me.

**Comment by ROKUMATE** [comment]
@samarthhapse A doubt for this issue that u want a Google Authentication login ... or is there other thing we need to do abt this issue ?
I have the Experience for Google Authentication setup ... So i can solve this issue as well ...

I am Also A GSSOC contributer ... So Do consider my contribution in it ...
