### ISSUE TITLE
 Implementing Multilingual support 

### ISSUE THREAD

**Issue by Anjankumarkamalapur** [samarthhapse/sarthi#62]
I'll make sure users can view the website in their preferred language by adding a language selection option in the navbar. Users will be able to choose from available languages for a smoother browsing experience. As previously done in my last project, I used the Google translation widget to translate content on the website into multiple languages.
The below image is my last project where I made it available in different languages.
![image](https://github.com/samarthhapse/sarthi/assets/139578011/9668f2de-205b-476b-8c2d-311a11a7fea7)

**Comment by samarthhapse** [comment]
okay , I am assigning this issue to you .Go ahead and create it till the endpoint and make a PR ,also finally when the app will be ready you must integrate it with the app.

**Comment by samarthhapse** [comment]
comment here with the expected submission date from your side

**Comment by samarthhapse** [comment]
@Anjankumarkamalapur are you working ?

**Comment by samarthhapse** [comment]
@Anjankumarkamalapur have you stated ?

**Comment by samarthhapse** [comment]
@Anjankumarkamalapur any reply ?

**Comment by samarthhapse** [comment]
@Anjankumarkamalapur you must reply , if you are raising issue ? You might not willing to work on , but you should inform.

**Comment by Anjankumarkamalapur** [comment]
Firstly I'm very sorry for not responding sir.I'm not available after
raising the issue due to health issues and I'm working on it I will let you
know in two days sir.

**Comment by samarthhapse** [comment]
No worries bro. Take care . This feature is not urgent . But just inform here once you start.
