### ISSUE TITLE
Otp while sign up

### ISSUE THREAD

**Issue by ayann07** [samarthhapse/sarthi#67]
I want to implement a functionality such that when user sign up then otp shall be sent to his email entered during registration, then user will enter that otp once verified, his account shall be created successfully.

Please assign me under gssoc'24

**Comment by ayann07** [comment]
@samarthhapse please assign me

**Comment by samarthhapse** [comment]
@ayann07  wait till tuesday

**Comment by samarthhapse** [comment]
@ayann07 comment on #67. If you are willing to work on it I will assign it to you

**Comment by ayann07** [comment]
Yes I want to work on it please assign it to me
