### ISSUE TITLE
filtering and displaying the experts of specific field from DB choosen by user

### ISSUE THREAD

**Issue by samarthhapse** [samarthhapse/sarthi#68]
TASK : after student login he must get three sections to choose 
1.Bug solving
2.Tech career assistance
3.Academic support
after selecting the section from above mentioned options , student must get list of all experts available in DB for the specific option

**Comment by ayann07** [comment]
Please assign it to me @samarthhapse

**Comment by samarthhapse** [comment]
@ayann07 you can go ahead. I am assigning it to you.

**Comment by samarthhapse** [comment]
added the details in first comment. Comment below with expected submission date from your side. Feel free to ask doubt if any !

**Comment by AbhiDiva96** [comment]
@samarthhapse I also want to work on this project. if there is no issue to @ayann07

**Comment by ayann07** [comment]
Sorry , but I will work on this @AbhiDiva96

**Comment by samarthhapse** [comment]
@ayann07 just comment the expected submission date from your side.

**Comment by ayann07** [comment]
2 june 2024

**Comment by samarthhapse** [comment]
@ayann07  , Is it ready ?

**Comment by ayann07** [comment]
Not yet, I'll complete this in 3 days.

**Comment by ayann07** [comment]
Basically it would be better once landing page is successfully completed. After that I complete this.

**Comment by ayann07** [comment]
Because UI would be according to the landing page only

**Comment by samarthhapse** [comment]
we can change ui part later, currently if basic functionality is ready you can make PR

**Comment by samarthhapse** [comment]
@ayann07 is it completed ?

**Comment by samarthhapse** [comment]
pls... make hurry , further features are getting deleted.

**Comment by samarthhapse** [comment]
@ayann07 also share .env file with me only

email => samarthhapse97@gmail.com

**Comment by ayann07** [comment]
Sure , I will do

**Comment by samarthhapse** [comment]
@ayann07 pls mention the EOD by which you will submit this issue ?

**Comment by samarthhapse** [comment]
@ayann07 try to raise PR by today only . Further work is getting delayed so much !
Also mail : .env credentials.

**Comment by ayann07** [comment]
I'll complete this by tomorrow. I had my exams that's why I was busy.

**Comment by samarthhapse** [comment]
okay @ayann07 , but just raise PR by tomorrow EOD. also share .env credentials on my mail.

**Comment by samarthhapse** [comment]
Hello @ayann07 , it is really getting too much delayed . Kindly raise PR by today afternoon only

**Comment by ayann07** [comment]
Sorry, but I am unable to do this. Please unassign me and assign someone else. I apologise for the same.

**Comment by samarthhapse** [comment]
@ayann07 if you want to take one more day,  you can. You have already wasted time since 3rd June. I hoped you were working

**Comment by samarthhapse** [comment]
Share .env credentials on my mail , samarthhapse97@gmail.com

**Comment by samarthhapse** [comment]
Are you unable , or want so.e time , just clear it

**Comment by ayann07** [comment]
I am unable to do this. Sorry for the inconvenience.

**Comment by samarthhapse** [comment]
Okay , just share the credentials of .env , backend is not running bcs of it

**Comment by samarthhapse** [comment]
@ayann07 just share the credentials immediately on samarthhapse97@gmail.com

**Comment by samarthhapse** [comment]
@ayann07 .env ??????

**Comment by samarthhapse** [comment]
@ayann07 share it immedietly

**Comment by ayann07** [comment]
Done sir

**Comment by samarthhapse** [comment]
@ayann07 okay

**Comment by samarthhapse** [comment]
Hello @ayann07 , I have an issue for you , If you are wiling, to work on #89 , pls comment there.
