### ISSUE TITLE
Preloader

### ISSUE THREAD

**Issue by Jagpreet153** [samarthhapse/sarthi#69]
@samarthhapse I would like to add a preloader to your site it would be responsive and matching the UI of your site . Kindly assign it me under GSSoC'24

**Comment by samarthhapse** [comment]
pls firstly send me the ss of the loader you will be using & it must be in dark jellyfish theme. I am assigning it to you make a PR after you are done with it.

**Comment by samarthhapse** [comment]
any update regarding the loader you are gonna use ! Pls send me ss of all possible cool loaders you can create

**Comment by Jagpreet153** [comment]
> any update regarding the loader you are gonna use ! Pls send me ss of all possible cool loaders you can create

Sure I am sending within few minutes

**Comment by Jagpreet153** [comment]
https://github.com/samarthhapse/sarthi/assets/119691733/55f467d8-8121-4f72-b4b4-a993d746a7a4

Dont worry the quality is poor due to screen size . It would be clear as a preloader because I would be using in JSON format

**Comment by samarthhapse** [comment]
don't you have any another one

**Comment by Jagpreet153** [comment]
> it's amazing ! but don't you have any another one

Of same theme ?

**Comment by samarthhapse** [comment]
ohhhh you took it in wrong way, jelly fish means not the jelly fish actually , I meant dark bluish background only

**Comment by Jagpreet153** [comment]
> ohhhh you took it in wrong way, jelly fish means not the jelly fish actually , I just meant dark bluish background only

Sorry for confusion... yes there are multiple animations wait...

**Comment by samarthhapse** [comment]
yess, pls share any related to our website's aim (bug,help,solution,computer,etc..)

**Comment by Jagpreet153** [comment]
https://github.com/samarthhapse/sarthi/assets/119691733/65d1c913-20c3-46c5-91a0-98b06bc0196c

**Comment by Jagpreet153** [comment]
https://github.com/samarthhapse/sarthi/assets/119691733/4e620fed-a08a-4963-8bc8-16b5bcc81986

**Comment by samarthhapse** [comment]
you can go with anyone as per your convenience. Just add it to codebase and make PR

**Comment by Jagpreet153** [comment]
Ok @samarthhapse I will raise a PR by tomorrow . Kindly add GSSoC'24 tag...
