### ISSUE TITLE
Creating Backend file Using MVC pattern

### ISSUE THREAD

**Issue by Crazzy-novus** [samarthhapse/sarthi#7]
I am interested in this project. I can structure a backend using Node.js, express and MongoDB. I thinks _MVC pattern_ fits best for this "sarthi" application. and I can integrate JWT token for authentication which make the webpage more secure. Please assign this Issue to me.

**Comment by Piyusharora2003** [comment]
hi @Crazzy-novus @samarthhapse i believe since we have a 3 month program would not it be better to make it a microservice based architecture though i am not the expert in the field but i believe it would be great for learning anyway do share your opinions

**Comment by Crazzy-novus** [comment]
Hello @Piyusharora2003 MVC is a **Design pattern** it separate the application into 1. Model part, 2. Controller part and 3. View part. MVC can used both in monolithic  and microservice architecture. [https://wisdomplexus.com/blogs/mvc-vs-microservices/](refer this To known more).  My intention is to make the backend server. Your thought is interesting .

**Comment by Piyusharora2003** [comment]
I want to say lets first fix what we want to develop . rather than just wandering around for contribution points in the GSSOC . yes the idea of building a MVC architecture is great but i want to emphasize on what will be the high level design for the implication

**Comment by Chandan157** [comment]
Hello sir, I am Chandan. Under GSSOC'24, I would like to work on this issue. can you assign this issue to me!!
