### ISSUE TITLE
chat feature for student and expert

### ISSUE THREAD

**Issue by samarthhapse** [samarthhapse/sarthi#70]
create the super cool UI for login and signup page. Cool animations and advanced react concepts must be used
Warning : strictly do not change the old react code's logic , just change the UI.

**Comment by akilesh1706** [comment]
@samarthhapse I would like to work on this as a part of GSSoC'24. Request you to assign it to me. Thanks!

**Comment by niteshbca** [comment]
@samarthhapse  Please assign to me issue under GSSOC’24.
I can fix this issue.
Thank You !

**Comment by Ankit389** [comment]
Hello sir 
I'm a GSSOC'24 contributor...i want to work on this issue please assign this task to me..i will complete this task with in one day and please assign label to it also

**Comment by n-keerthi-gayathri** [comment]
Hello @samarthhaps, I am GSSOC'24 contributor can you assign me this task

**Comment by KhushiPrasad** [comment]
Hello @samarthhapse , I am a GSSOC contributor, I would like to work on this issue, please assign this to me.

**Comment by Priyanshu2743** [comment]
Hii @samarthhapse 
i could create a Great UI for login and signin using 
Using different effects like Glass morphism effect, Vanilla Js Effect

**Comment by samarthhapse** [comment]
First ficus on exams and then work on it

**Comment by samarthhapse** [comment]
hello @Priyanshu2743 , this a new issue for you. As I mentioned in #90 that I will assign you the frontend task

**Comment by samarthhapse** [comment]
jelly has added backend for this part. You just need to complete step 2

**Comment by samarthhapse** [comment]
as student signin and choose any expert he must get the complete info about the expert

now , as student selects an expert he must be able to see the complete profile page of expert (with complete data that expert have updated )

**Comment by samarthhapse** [comment]
@Priyanshu2743 pls raise PR by tomorrow afternoon only. It has been delayed already

**Comment by Priyanshu2743** [comment]
Actually, I am not able to do this by today as I am travelling since 13 June due to some unavoidable reasons 

Kindly, Provide me some time till a day after tomorrow (19 June).

**Comment by samarthhapse** [comment]
@Aditijainnn , can you work on this isuue

**Comment by samarthhapse** [comment]
TASK : A chat feature for student and an expert to chat within both of them only 

@Ankit389 , @Priyanshu2743, @Aditijainnn , @n-keerthi-gayathri , @akilesh1706  I just need chat functionality , if any of you can integrate it within 2 days pls comment below

**Comment by samarthhapse** [comment]
@Ankit389 , available to work on payment gateway ?

**Comment by samarthhapse** [comment]
@Aditijainnn available to work on payment gateway ?

**Comment by Ankit389** [comment]
Yes sir, I will complete the payment gateway tonight.

**Comment by Ankit389** [comment]
Please assign to me

**Comment by samarthhapse** [comment]
@akilesh1706 just comment on #201 , I will assign and raise by today afternoon if possible
