### ISSUE TITLE
want to build step 2

### ISSUE THREAD

**Issue by AbhiDiva96** [samarthhapse/sarthi#71]
## want to build step-2 of student/juniors can choose their problem

![Screenshot 2024-05-26 221459](https://github.com/samarthhapse/sarthi/assets/112077897/429b3330-2284-40d2-a5ff-1f5163d97666)

**Comment by samarthhapse** [comment]
@AbhiDiva96 I have already assigned it to ayaan07. Let him work on it, after reviewing his code if there will be any changes the I will surely assign them to you only !

**Comment by AbhiDiva96** [comment]
ok got it.
