### ISSUE TITLE
Home page need advanced and attractive frontend 

### ISSUE THREAD

**Issue by AbhiDiva96** [samarthhapse/sarthi#72]
## According to the requirement of sarthi. the common homepage (student and expert) need more improvement and attractive using advance UI stuff.

assigned it under the gssoc'24
@samarthhapse 

## current Common homepage

![Screenshot 2024-05-27 013017](https://github.com/samarthhapse/sarthi/assets/112077897/1bd0be22-46a9-4157-9701-189635dcf07a)

**Comment by samarthhapse** [comment]
Hello @AbhiDiva96 , this page cannot be our main hoepage. The task of creating homepage is on the edge of completion already. We have to serve this page whenever user clicks on login button on that main homepage.
You can start making his page more attractive.

**Comment by samarthhapse** [comment]
also this issue is created on #70 , justping me there there , I will assign this page to you

**Comment by samarthhapse** [comment]
@AbhiDiva96 you can work on this issue

**Comment by samarthhapse** [comment]
https://github.com/samarthhapse/sarthi/assets/131296047/eaa982cc-6bc3-4e58-a362-946538dc56a4

**Comment by samarthhapse** [comment]
try to make it in dark theme and responsive

**Comment by samarthhapse** [comment]
Firstly just comment if you are willing to work , do not start directly , I have to merge one PR before you start. Let me first erge that Pr then start working on this

**Comment by AbhiDiva96** [comment]
Ok TQ so much.
And one more thing if you have made the  architecture of sarthi just ping me. It will give me basic Idea to create robust frontend of sarthi.

**Comment by samarthhapse** [comment]
Don't start immediately , I have to merge one PR tomorrow. I will comment here then you can start.

**Comment by AbhiDiva96** [comment]
hey @samarthhapse .
If you don’t mind I have just build some architecture of the Sarthi. Add your comment

![2DB12F3C-88A4-4ECA-8BAE-B69D54853C50](https://github.com/samarthhapse/sarthi/assets/112077897/17ab081b-553b-43e5-a030-c681c2477a8c)

**Comment by AbhiDiva96** [comment]
> try to make it in dark theme and responsive

I have built all thing in dark mode

**Comment by samarthhapse** [comment]
Great ! it is absolutely correct.

**Comment by samarthhapse** [comment]
@AbhiDiva96 now you can start working for this issue. I have added you as assignee

**Comment by AbhiDiva96** [comment]
ok @samarthhapse

**Comment by AbhiDiva96** [comment]
## My background is dark blue and your and ayaan's background is white ??

![Screenshot 2024-06-02 121456](https://github.com/samarthhapse/sarthi/assets/112077897/b3ee62c3-3585-4903-a5da-6a9340403fe7)
