### ISSUE TITLE
Dark/Light mode 

### ISSUE THREAD

**Issue by Jagpreet153** [samarthhapse/sarthi#77]
I would like to add dark /light toggle mode button to switch between dark and light modes . Kindly assign this task to me under GSSoC'24 .

**Comment by aryan-1309** [comment]
Please Assign this to me under GSSOC'24.

**Comment by Jagpreet153** [comment]
@samarthhapse Please respond to the issue

**Comment by samarthhapse** [comment]
@Jagpreet153 start working on this issue . I am adding you as assignee

**Comment by samarthhapse** [comment]
@Ankit389 can you create a single home page if you are provided with the reference design ?

**Comment by Jagpreet153** [comment]
@samarthhapse Please add gssoc and level tags

**Comment by samarthhapse** [comment]
@Jagpreet153 started ?

**Comment by Jagpreet153** [comment]
Yes @samarthhapse . I will raise the pr by tomorrow

**Comment by samarthhapse** [comment]
sure

**Comment by samarthhapse** [comment]
raise it with the working video

**Comment by samarthhapse** [comment]
also once check , why the pre-loader is not working

**Comment by Jagpreet153** [comment]
Ok @samarthhapse I will add another issue for preloader bug . Kindly assign it to me
