### ISSUE TITLE
Modern landing page 2

### ISSUE THREAD

**Issue by Abhishek-465** [samarthhapse/sarthi#8]
I can work on creating the Login and register page UI and if necessary i can also integrate firebase for authentication. Otherwise i can also write backend in addition to frontend using node js and mongo db but since someone already created that issue i am not doing that.
@samarthhapse  Kindly assign me.
Working under GSSOC 24

**Comment by sakshi-thakare** [comment]
I can fix this issue under Gssoc'24 ,assign it to me

**Comment by AbhiDiva96** [comment]
I have worked several times to build login or sign-up pages for frontend using javascript /typescript and react js/next js.  

I eagerly want to contribute to this project. @samarthhapse 

Can you pls assign me this issue.

**Comment by IP80808080** [comment]
👋 Hello! I'd be happy to help with this issue. Could you please assign it to me? Additionally, could you please label it for the appropriate level? Thank you! 🚀

**Comment by devu007** [comment]
I would love to work on this issue please assign it to me.

**Comment by samarthhapse** [comment]
@Abhishek-465 let me once add UI design of project in Learn.md then you can start working on this issue.

**Comment by Jatingupta9120** [comment]
assign this issue to me under gsoc 24

**Comment by Aryan-joh** [comment]
HIi sir i want to work on this as i have the experience in this please assign this to me

**Comment by Annu1809** [comment]
@samarthhapse please assign it to me .

**Comment by codershrutik** [comment]
@samarthhapse I have extensive experience working in front-end development, and have expertise in HTML, CSS and JavaScript, as well as the MERN stack. I can create a LogIn page frontend. Please assign this use to me as part of GSSOC'24.

**Comment by poojaverma9578** [comment]
I would like to make a significant contribution in this project as a GSSOC'24 contributor,please assign me this .

**Comment by Dev-AyushTrivedi** [comment]
Hi there!
As a contributor in GSSoC 24 with a strong command in web design, i can create interactive designs, I'd like to take on this issue. Could you please assign it to me? Looking forward to contributing!

**Comment by Chandan157** [comment]
Hello sir, I am Chandan. Under GSSOC'24, I would like to work on this issue. can you assign this issue to me!!

**Comment by Rajneeshkarya** [comment]
Hi @Abhishek-465. I would like to do this task under GSSOC'24

**Comment by magrawal6902** [comment]
I am a frontend developer and I like to create frontend pages. As this issue includes making a modern frontend. I would like to draw the owners attention towards me and my repositories. I am creating animated websites using GSAP, Scroll trigger, Locomotive, Lenis, SheryJs and much more. I can assure i can be the best frontend developer
Please assign me this task under Gssoc'24.

**Comment by samarthhapse** [comment]
@Abhishek-465 I have created and assigned this issue in #10 , but I will add UI design in Learn.md within 2 days. Then you can collaborate in issue #10 to for the frontend part

**Comment by Abhishek-465** [comment]
@samarthhapse Okay then i will collaborate on that issue after you add the UI design.

**Comment by Satwik-Kar** [comment]
This issue caught my eye, and I'm curious to dig in. Let's team up and crack this one together! Excited to work on it with you!
@samarthhapse . Kindly assign me this issue under **GSSOC'24**

**Comment by Akshatakapare** [comment]
I would like to contribute to this issue as I have done many projects as well as won hackathons. Could you please consider assigning this issue to me? I'm committed to dedicating my time and effort to delivering a high-quality design that aligns with the project's goals.

Looking forward to the opportunity to work on this exciting project!

**Comment by shrerai** [comment]
Hello I would like to contribute on this. Please assign me this issue under GSSOC'24.

**Comment by mtg718** [comment]
@samarthhapse please assign this issue to me under GSSoc'24.

**Comment by shuhaki** [comment]
hey@samarthapse i have good experince in this..... i want to this please assign me

**Comment by samarthhapse** [comment]
@Abhishek-465 please comment on #14 . Here there is one more contributor for landing page. We will discuss and you both can collaborate to create.

**Comment by Yuvraj960** [comment]
@samarthhapse Please assign this issue to me under GSSoC24

**Comment by samarthhapse** [comment]
Hello everyone there , comment on #70  if you are experienced in advanced react and tailwind and willing to work on same signup and login page to update the old simple one in to the super cool page with attention seeking animations and much more changes in UI only

**Comment by samarthhapse** [comment]
Hello everyone there #90 if you are experienced in advanced react and tailwind and willing to work on same signup and login page to update the old simple one in to the super cool page with attention seeking animations and much more changes in UI only

**Comment by Gokilp** [comment]
Can asssign to me I working on issue

**Comment by samarthhapse** [comment]
@AbhiDiva96 completed with exams ?

**Comment by samarthhapse** [comment]
@Abhishek-465 can you work on level3 issue

**Comment by AbhiDiva96** [comment]
Yaah I just completed now I am free. I am happy to work on this project @samarthhapse

**Comment by samarthhapse** [comment]
okay , @AbhiDiva96 

Can you work on creating a chat feature. Backend in node and express is already added. You just need to create frontend in React.js and connect it with backend

**Comment by AbhiDiva96** [comment]
Sure I will work on it @samarthhapse .
Assigned me the issue if you created.
Else let me know to create the issue

**Comment by samarthhapse** [comment]
okay @AbhiDiva96 , pls comment on => https://github.com/samarthhapse/sarthi/issues/11 . I will provide you description of issue immedietly.

You can create very simple frontend but just make sure to connect backend properly

**Comment by samarthhapse** [comment]
@Abhishek-465 , available for MERN issues ?

**Comment by Abhishek-465** [comment]
@samarthhapse  Sorry i won't be available.
