### ISSUE TITLE
creating landing page similar to provided reference design

### ISSUE THREAD

**Issue by samarthhapse** [samarthhapse/sarthi#83]

**Comment by AbhiDiva96** [comment]
i would like to build @samarthhapse

**Comment by samarthhapse** [comment]
For this first I have to merge one pr tomorrow. Till then complete #72 . Then we will get back to this issue

**Comment by AbhiDiva96** [comment]
ok, got it

**Comment by KhushiPrasad** [comment]
Hello @samarthhapse , I am a GSSOC contributor, I would like to work on this issue, please assign me.
