### ISSUE TITLE
Addition Of Navbar and interactive UI

### ISSUE THREAD

**Issue by Priyanshu2743** [samarthhapse/sarthi#87]
Hii @samarthhapse, 

I will add the Navbar ,Footer and Interactive UI for the different section in this Issue

Kindly assign me this task and add label of level and gdsoc

**Comment by Priyanshu2743** [comment]
I will complete the work Left in the UI 
PR #86

**Comment by Aradhyajha** [comment]
Hii  @samarthhapse, i want to work on this issue , please assign me this task   
This issue involves enhancing the web application by adding a responsive navigation bar (navbar) and interactive UI elements. The task includes designing a navbar with links to Home, About, Services, and Contact sections, ensuring it is responsive and mobile-friendly. JavaScript will be used to implement smooth scrolling and dynamically display content when a navbar link is clicked, with a default section shown on page load. Utilizing a CSS framework like Bootstrap is recommended for improved design and responsiveness, along with adding basic accessibility features to ensure usability for all users. This task aims to improve the website's navigation and user experience, making it an excellent opportunity to develop frontend development skills.

**Comment by samarthhapse** [comment]
@Aradhyajha , pls start

**Comment by samarthhapse** [comment]
@Aradhyajha , pls try to complete by tomorrow EOD

**Comment by Aradhyajha** [comment]
Ok sir sure

**Comment by Aradhyajha** [comment]
@samarthhapse , can u please guide me how to proceed on this issue and how do  i make changes on the navbar

**Comment by samarthhapse** [comment]
@Aradhyajha pls share screenshot of current navbar

**Comment by Aradhyajha** [comment]
![navbar](https://github.com/samarthhapse/sarthi/assets/130289875/fd0bbdd7-8754-45fe-b78c-cd5d12f32237)



![Uploading nav_bar.jpg…]()

**Comment by Aradhyajha** [comment]
![Uploading nav_bar.jpg…]()

**Comment by Aradhyajha** [comment]
![Uploading navbar_issue.jpg…]()

**Comment by samarthhapse** [comment]
Increase font size of "sarthi" and make it more bold and change it's color to dark blue

**Comment by samarthhapse** [comment]
remove dropdown of resources , keep it simple like other li

**Comment by samarthhapse** [comment]
now you can raise PR

**Comment by samarthhapse** [comment]
do you have experience in three.js

**Comment by Aradhyajha** [comment]
Ok sir I will try to resolve this issue as soon as possible

**Comment by Aradhyajha** [comment]
@samarthhapse  sir, can you please assign label to this issue no.  #87

**Comment by Aradhyajha** [comment]
@samarthhapse sir, please assign level to this issue no #87

**Comment by samarthhapse** [comment]
see @Aradhyajha , I already mentioned that I will merge PR in 2-3 days. Pls have patience , I have record of everything , I will add levels and all things. Also pls do not comment on any random issue for assigning it . It creates lot of conflicts and confusions. I have record of all contributors. I will surely assign issues to you which are for you.

**Comment by Aradhyajha** [comment]
Ok sir

**Comment by samarthhapse** [comment]
@Aradhyajha , assigning of issue and adding labels is done. Thanks for resolving
