### ISSUE TITLE
Voice message is not working.

### ISSUE THREAD

**Issue by mukilan2815** [samarthhapse/sarthi#88]
**Describe the bug**
When i press mic icon voice msg is not working.

**To Reproduce**
1. Go to 'Meet'
2. Click on 'Mic icon'
3.  See error

**Expected behavior**
When user press mic icon it should get the voice msg and display in output
**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Assign me this task under GSSOC'24

**Comment by samarthhapse** [comment]
fork temp branch of repo now. Make a proper screen recording and point with cursor where you are saying and share it here.

**Comment by samarthhapse** [comment]
@mukilan2815 are you working on it ?

**Comment by mukilan2815** [comment]
Assign me for GSSOC'24 i will make this

**Comment by samarthhapse** [comment]
complete it end to end , so we can add it in chatting functionality as a 'mic icon'. Comment below the EOD by which you will complete it ?

**Comment by iLakshya** [comment]
@Jagpreet153 please assign this issue to me

**Comment by Jagpreet153** [comment]
> @Jagpreet153 please assign this issue to me

Sorry , but I am not the admin of this repository....

**Comment by samarthhapse** [comment]
hello @iLakshya I am admin. I am assigning this issue to you. Please try to complete by 12 EOD

**Comment by samarthhapse** [comment]
@iLakshya , working or not ?

**Comment by samarthhapse** [comment]
Or let me assign it to @mukilan2815

**Comment by iLakshya** [comment]
Yes I am working on the same. Give me 1 more day

**Comment by samarthhapse** [comment]
sure
