### ISSUE TITLE
google meet integration

### ISSUE THREAD

**Issue by samarthhapse** [samarthhapse/sarthi#89]
reference => https://github.com/0x5eba/Video-Meeting

**Comment by Ajitesh1705** [comment]
Hey Samarth, can you please elaborate on how you want the integration to be incorporated to the project? I would be delighted to help you on this

**Comment by samarthhapse** [comment]
We have to provide simple feature of online meet to help the student and expert to solve their doubts , etc.

**Comment by Priyanshu2743** [comment]
I can provide this feature to the website 
with a UI 

kindly assign me this issue

**Comment by Ajitesh1705** [comment]
Understoof,  I think we can do that, I can start working on this at the earliest , if you assign me the issue.

**Comment by samarthhapse** [comment]
Okay @Ajitesh1705 start working , and give me updates daily. I think you can do it. But if you are now working or can't work so pls inform me immediately.  I am counting on you from today. Just keep commenting here daily.

**Comment by Ajitesh1705** [comment]
Alright, thank you, I will familiarise myself with the code and will let you know about the updates tomorrow. Won't let you down.

**Comment by samarthhapse** [comment]
@Ajitesh1705  any updates ?

**Comment by samarthhapse** [comment]
@Ajitesh1705 comment the updates ?

**Comment by samarthhapse** [comment]
@Ajitesh1705 is it done ?

**Comment by samarthhapse** [comment]
@Ajitesh1705 when will you raise the PR

**Comment by samarthhapse** [comment]
@Ajitesh1705 , It seemed like you were inactive from last 2 weeks. I have unassigned you

**Comment by samarthhapse** [comment]
@Priyanshu2743 , can you work on this , I have also share the reference in description

**Comment by KavyaBS123** [comment]
Hey @samarthhapse can you please assign me this issue 
I would like to work on it

**Comment by samarthhapse** [comment]
@KavyaBS123 assigned this issue to you. Pls try to raise PR within 4 to 5 days. You can start working

**Comment by KavyaBS123** [comment]
Sure I will

**Comment by samarthhapse** [comment]
@KavyaBS123 , hope doing well. Ask  doubt if any. Just don't let a single day go as a blocker

**Comment by KavyaBS123** [comment]
Yup sure, I am working on it , I have my exams going on therfore day seems to be packed  fully , but I ensure to do it within time don't worry

**Comment by samarthhapse** [comment]
@KavyaBS123 yeah !

**Comment by samarthhapse** [comment]
@KavyaBS123 completed ? Please raise PR

**Comment by KavyaBS123** [comment]
Yeahh su

**Comment by samarthhapse** [comment]
@KavyaBS123 raising PR today ?

**Comment by samarthhapse** [comment]
@KavyaBS123 Pls raise PR if completed.

**Comment by samarthhapse** [comment]
@KavyaBS123 any updates

**Comment by samarthhapse** [comment]
@KavyaBS123 done with it OR working ?

**Comment by samarthhapse** [comment]
@KavyaBS123 , deadline is already over

**Comment by samarthhapse** [comment]
@KavyaBS123 any updates from your side

**Comment by samarthhapse** [comment]
@KavyaBS123 , raising PR today

**Comment by samarthhapse** [comment]
@KavyaBS123 , why so inactive

**Comment by samarthhapse** [comment]
@KavyaBS123 , just comment whatever issue you are facing

**Comment by samarthhapse** [comment]
@KavyaBS123 , project is getting delayed bcs of such issues

**Comment by samarthhapse** [comment]
@KavyaBS123 deadline is over

**Comment by samarthhapse** [comment]
@KavyaBS123 raise PR asap

**Comment by samarthhapse** [comment]
@KavyaBS123 just inform , if not possible to complete

**Comment by samarthhapse** [comment]
@KavyaBS123 project is getting delayed

**Comment by samarthhapse** [comment]
@KavyaBS123 , final call

**Comment by samarthhapse** [comment]
@KavyaBS123 raise PR by today EOD

**Comment by samarthhapse** [comment]
@KavyaBS123 OR I am unassigning you tomorrow
