### ISSUE TITLE
expert profile page ( only UI development of => profile picture , details , chat button , payment button , rating feature )

### ISSUE THREAD

**Issue by samarthhapse** [samarthhapse/sarthi#90]
when expert signs up his data gets stored in DB and further when he log in , you should be able to get that data from backend and display expert's profile page

**Comment by TheNikhilRaj** [comment]
I would like to work on this issue , please assign this to me.
@samarthhapse

**Comment by AakankshaSarode** [comment]
@samarthhapse  please assign me this issue under gssoc . I want to work on this issue.

**Comment by samarthhapse** [comment]
when expert signs up and further when he log in , you should be able to display that data from backend and display expert's profile page

**Comment by Priyanshu2743** [comment]
Hii @samarthhapse 

I can design the UI for this 
Kindly assign me this under gssoc and add label level

**Comment by samarthhapse** [comment]
@Priyanshu2743 can you complete 100 % it as per description

**Comment by Priyanshu2743** [comment]
can done easily but takes time 5 days as I have my exam tomorrow and on 8 June 
could make a pr on and after 8

**Comment by Priyanshu2743** [comment]
Could you please Assign me this 
I will try to complete and provide on and before 10 June

**Comment by jelly-afk** [comment]
@samarthhapse i can work on this but i need more info, like:
expert should provide and avatar pic when he signs up?

**Comment by jelly-afk** [comment]
alright, would you like me to a feature where an expert should provide a avatar which will be store in cloudinary and a small description about himself?

**Comment by samarthhapse** [comment]
Yeah, you can add it .

**Comment by jelly-afk** [comment]
alright so can you open an issue for the avatar and cloudinary integration? i will resolve that first

**Comment by samarthhapse** [comment]
#158

**Comment by Priyanshu2743** [comment]
I will provide this code to you as soon as I reach home 

I will reach home by 17 Morning

**Comment by samarthhapse** [comment]
Currenttly, I have assigned this task to @jelly-afk

**Comment by samarthhapse** [comment]
as soon as @jelly-afk completes this task , I will assign task of frontend of same issue to you priyanshu

**Comment by samarthhapse** [comment]
![Screenshot 2024-06-15 153209](https://github.com/samarthhapse/sarthi/assets/131296047/5b882cbe-acfb-4b52-86d4-ed87497e75ca)

like this , but only dark blue color for complete name "sarthi"

**Comment by samarthhapse** [comment]
do by evening only

**Comment by jelly-afk** [comment]
i have not started working on this, let him resolve this issue since he is already coding for this

**Comment by samarthhapse** [comment]
@jelly-afk  just complete the backend part then I will assign frontend to him in another issue. Bcs multiple functionalities are relayed on this issue.

**Comment by jelly-afk** [comment]
@samarthhapse can you elaborate more? what functionalities i have to add in backend?

**Comment by samarthhapse** [comment]
okay @jelly-afk 

step 1 : 
as expert signs-up/signin direct him to his profile page where he can edit information (which he have filled during signup)
+
additional data ( skills ,experience, edu.qualification )


step 2 : 

as in previous PR you are fetching the experts on student sign-in

now , as student selects an expert he must be able to see the complete profile page of expert (with complete data that expert have updated in step 1)

**Comment by samarthhapse** [comment]
@jelly-afk feel free to ask doubt , if any

**Comment by samarthhapse** [comment]
@jelly-afk pls make sure to fork code from current (temp) branch only as multiple PRs are merged today.

**Comment by jelly-afk** [comment]
@samarthhapse all of this has to be done in frontend, only backend feature here is edit profile for expert, correct?

**Comment by samarthhapse** [comment]
yeah @jelly-afk  ! but managing these things between two contributors can be confusing for both oy you. I suggest you to work completely on this issue. Integrate backend end to end & for frontend part just create very simpler UI. Further I will assign the advancements of frontend to Priyanshu

**Comment by samarthhapse** [comment]
@jelly-afk any update ? as it is Sunday , the holiday. Can you try to complete it by EOD ? Further so many functionalities are pending

**Comment by jelly-afk** [comment]
@samarthhapse i have added the expert Home Page where he can edit his details but i have to fix other bugs to make it work

**Comment by samarthhapse** [comment]
@jelly-afk , added labels of VSoC'24 to all your current and previous PR's . Also added BONUS points for 2 of them
