### ISSUE TITLE
Adding animations in UI

### ISSUE THREAD

**Issue by samarthhapse** [samarthhapse/sarthi#91]

**Comment by VaibhavYT** [comment]
I want to work on this please assign me.

**Comment by samarthhapse** [comment]
@VaibhavYT you can share your attention seeking work here

**Comment by KhushiPrasad** [comment]
Hello @samarthhapse , I am GSSOC contributor , I would like to work on this issue, please assign me.

**Comment by samarthhapse** [comment]
@VaibhavYT are you working or I should assign to @KhushiPrasad

**Comment by VaibhavYT** [comment]
Assign me this I am working on adding very attractive animantios.

**Comment by samarthhapse** [comment]
Currently do no add any animation on home page as It is getting changed within 3-4 days. Add animations for the pages I am sharing below

**Comment by samarthhapse** [comment]
![Screenshot 2024-06-05 124259](https://github.com/samarthhapse/sarthi/assets/131296047/5af28fd0-72c1-4570-88f0-1f00f402efe6)

**Comment by samarthhapse** [comment]
2. => signup pagen (student & expert)
3. => signin page (student & expert)

**Comment by samarthhapse** [comment]
currently add animations in above 3 pages. Further I will raise new issue for homepage animations

**Comment by samarthhapse** [comment]
as there are 3 pages I am updating issue from level 1 to level 2.  Comment with the EOD by which you can submit

**Comment by VaibhavYT** [comment]
I have started

**Comment by samarthhapse** [comment]
I think you have raise one more issue, for UI of whole app. First focus and complete this issue (3 pages mentioned above ) as early as you can. If your work will be attention seeking ,I will surely assign that issue to you only.

**Comment by samarthhapse** [comment]
currently focus here , and hurry up !

**Comment by VaibhavYT** [comment]
I have created an PR you #108  you can please check

**Comment by samarthhapse** [comment]
Great work , had some issues with previous PR , just raise the PR again

**Comment by VaibhavYT** [comment]
Thank you for appreciation 😊✅ I have raised an PR #112
