### ISSUE TITLE
Home page UI design can be improved

### ISSUE THREAD

**Issue by AakankshaSarode** [samarthhapse/sarthi#96]
![Screenshot 2024-06-04 102100](https://github.com/samarthhapse/sarthi/assets/142107143/0d12b324-a726-46ff-bb12-65ccf84216b0)

**Comment by AakankshaSarode** [comment]
@samarthhapse  please  assign me this issue under gssoc. I want to work on this issue.

**Comment by samarthhapse** [comment]
I have assigned this issue elsewhere , If you are willing to work on #90  pls comment there.

**Comment by samarthhapse** [comment]
@
