### ISSUE TITLE
Preloader

### ISSUE THREAD

**Issue by Jagpreet153** [samarthhapse/sarthi#98]
**Describe the bug**
Preloader not working 

**To Reproduce**
Reload the page

**Expected behavior**
A animation should render while the page is being loaded

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [e.g. chrome

**Additional context**
Kindly assign this issue to me under GSSoC'24

**Comment by samarthhapse** [comment]
@Jagpreet153 start and raise PR by today if possible. I am assigning to you.
